### ISSUE TITLE
Subnet Service Endpoints & Route Tables

### ISSUE THREAD

**Issue by rdtechie** [Azure/azure_preview_modules#138]
Are there plans to add service endpoints and route tables to the azure_rm_subnet module?

**Comment by rdtechie** [comment]
Somebody?

**Comment by yuwzho** [comment]
Hi @rdtechie Sorry for late reply, our team just back from National holiday.

Route tables in azure_rm_subnet is just support a few days ago with [Ansible v2.7](https://docs.ansible.com/ansible/latest/modules/azure_rm_subnet_module.html?highlight=azure_rm_subnet#parameters)'s release. You can install the latest version and have a try. To create a route  table, you can use [`azure_rm_routetable`](https://docs.ansible.com/ansible/latest/modules/azure_rm_routetable_module.html?highlight=azure_rm_subnet) module.

And service endpoints is not supported yet and we can leverage our plan to do it. However, according to Ansible's release guideline, even we add such new  option right now, you cannot view it in an official release until next major release (v2.8)

**Comment by rdtechie** [comment]
> Hi @rdtechie Sorry for late reply, our team just back from National holiday.
> 
> Route tables in azure_rm_subnet is just support a few days ago with [Ansible v2.7](https://docs.ansible.com/ansible/latest/modules/azure_rm_subnet_module.html?highlight=azure_rm_subnet#parameters)'s release. You can install the latest version and have a try. To create a route table, you can use [`azure_rm_routetable`](https://docs.ansible.com/ansible/latest/modules/azure_rm_routetable_module.html?highlight=azure_rm_subnet) module.
> 
> And service endpoints is not supported yet and we can leverage our plan to do it. However, according to Ansible's release guideline, even we add such new option right now, you cannot view it in an official release until next major release (v2.8)

Thank you very much! I'm perfectly fine to use the preview modules, so if your team can build a service endpoints property into this module, I would be very happy.

**Comment by Fred-sun** [comment]
@rdtechie Thanks for your try, I will try on tomorrow! Thanks!

**Comment by rdtechie** [comment]
Hi @Fred-sun , did you managed to reproduce the issue?

**Comment by Fred-sun** [comment]
@rdtechie Do you meet error like this? 
```e.g.
TASK [Update the subnet] *******************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'locations'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/fred/.ansible/tmp/ansible-tmp-1550215303.15-37620556730530/AnsiballZ_azure_rm_subnet.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/fred/.ansible/tmp/ansible-tmp-1550215303.15-37620556730530/AnsiballZ_azure_rm_subnet.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/fred/.ansible/tmp/ansible-tmp-1550215303.15-37620556730530/AnsiballZ_azure_rm_subnet.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_azure_rm_subnet_payload_zGCAZ0/__main__.py\", line 387, in <module>\n  File \"/tmp/ansible_azure_rm_subnet_payload_zGCAZ0/__main__.py\", line 383, in main\n  File \"/tmp/ansible_azure_rm_subnet_payload_zGCAZ0/__main__.py\", line 228, in __init__\n  File \"/tmp/ansible_azure_rm_subnet_payload_zGCAZ0/ansible_azure_rm_subnet_payload.zip/ansible/module_utils/azure_rm_common.py\", line 310, in __init__\n  File \"/tmp/ansible_azure_rm_subnet_payload_zGCAZ0/__main__.py\", line 286, in exec_module\nKeyError: 'locations'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
	to retry, use: --limit @/home/fred/task/azure_138/task.retry

**Comment by Fred-sun** [comment]
@yuwzho Can you help me to confirm that specifying the location parameter is the necessary to the service endpoint? Thanks!

**Comment by yuwzho** [comment]
@Fred-sun Please try https://github.com/ansible/ansible/pull/52312

**Comment by Fred-sun** [comment]
@yuwzho Test fail, same error info

**Comment by Fred-sun** [comment]
@rdtechie Thanks for your report, This bug has been fixed by [#52312](https://github.com/ansible/ansible/pull/52312). I have test and get success result, Thanks!

**Comment by rdtechie** [comment]
Thanks @Fred-sun & @yuwzho! Please help me understand how the process goes. The team merges into the devel branch of the Ansible core engine from https://github.com/Azure/azure_preview_modules ? When will the change pop up into https://github.com/Azure/azure_modules ? What's actually the difference between the two?

**Comment by Fred-sun** [comment]
@rdtechie The Azure_preview_modules role is the most complete and includes all the latest Azure modules. The update and bug fix are done in a more timely manner than official Ansible release. If you use Ansible for Azure resource provisioning purpose, you're strongly encouraged to install this role.
    But the azure_modules role include the latest changes and bug fixes for Azure modules from the devel branch of Ansible repository. If you cannot wait for Ansible's next release, installing this role is a god choice. 
Thanks!

**Comment by yuwzho** [comment]
@rdtechie  As Fred mentioned, you can now try this fix with this azure_preview_module role or install the Ansible very latest bit. And the azure_modules' release cycle is every Wednesday UTC time with manual approval.
