### ISSUE TITLE
azure_rm_keyvaultkey is failing No handlers could be found for logger \"msrestazure.azure_active_directory

### ISSUE THREAD

**Issue by abelgana** [Azure/azure_preview_modules#144]
Hi, 
I have troubles using azure_rm_keyvaultkey. This is how to reproduce the issue.

```
docker
 run -it centos:7.4.1708 bash
inside the container
yum check-update; sudo yum install -y gcc libffi-devel python-devel openssl-devel epel-release
yum install -y python-pip python-wheel
pip install ansible[azure]
export AZURE_SUBSCRIPTION_ID=<your-subscription_id>
export AZURE_CLIENT_ID=<security-principal-appid>
export AZURE_SECRET=<security-principal-password>
export AZURE_TENANT=<security-principal-tenant>
export AZURE_CLOUD_ENVIRONMENT=AzureChinaCloud
```

the following module works:

```
---
- hosts: localhost
  connection: local
  tasks:
    - name: Create a resource group
      azure_rm_resourcegroup:
        name: ansible-rg
        location: eastus
      register: rg
    - debug:
        var: rg
```

But when I try to use azure_rm_keyvaultkey:
```
---
- hosts: localhost
  connection: local
  tasks:
    - name: create a secret
      azure_rm_keyvaultkey:
        key_name: MyKey
        keyvault_uri: https://ansibletest.vault.azure.cn/
```

I have the following error:

```fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "No handlers could be found for logger \"msrestazure.azure_active_directory\"\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-xxx-xxx/AnsiballZ_azure_rm_keyvaultkey.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-xxxxx.3-xxxxxx/AnsiballZ_azure_rm_keyvaultkey.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-xxxx.3-xxx/AnsiballZ_azure_rm_keyvaultkey.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_azure_rm_keyvaultkey_payload_gNrmri/__main__.py\", line 296, in <module>\n  File \"/tmp/ansible_azure_rm_keyvaultkey_payload_gNrmri/__main__.py\", line 292, in main\n  File \"/tmp/ansible_azure_rm_keyvaultkey_payload_gNrmri/__main__.py\", line 133, in __init__\n  File \"/tmp/ansible_azure_rm_keyvaultkey_payload_gNrmri/ansible_azure_rm_keyvaultkey_payload.zip/ansible/module_utils/azure_rm_common.py\", line 311, in __init__\n  File \"/tmp/ansible_azure_rm_keyvaultkey_payload_gNrmri/__main__.py\", line 164, in exec_module\n  File \"/tmp/ansible_azure_rm_keyvaultkey_payload_gNrmri/__main__.py\", line 200, in get_key\n  File \"/usr/lib/python2.7/site-packages/azure/keyvault/key_vault_client.py\", line 441, in get_key\n    response = self._client.send(request, header_parameters, **operation_config)\n  File \"/usr/lib/python2.7/site-packages/msrest/service_client.py\", line 257, in send\n    **kwargs)\n  File \"/usr/lib/python2.7/site-packages/requests/sessions.py\", line 512, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/usr/lib/python2.7/site-packages/requests/sessions.py\", line 629, in send\n    r = dispatch_hook('response', hooks, r, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/requests/hooks.py\", line 31, in dispatch_hook\n    _hook_data = hook(hook_data, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/azure/keyvault/custom/key_vault_authentication.py\", line 146, in _handle_401\n    security = self._get_message_security(prep, challenge)\n  File \"/usr/lib/python2.7/site-packages/azure/keyvault/custom/key_vault_authentication.py\", line 172, in _get_message_security\n    scheme))\n  File \"/usr/lib/python2.7/site-packages/azure/keyvault/custom/key_vault_authentication.py\", line 61, in _auth_callback_compat\n    if len(inspect.getargspec(self._user_callback).args) == 3 \\\n  File \"/tmp/ansible_azure_rm_keyvaultkey_payload_gNrmri/__main__.py\", line 153, in auth_callback\n  File \"/usr/lib/python2.7/site-packages/msrestazure/azure_active_directory.py\", line 453, in __init__\n    self.set_token()\n  File \"/usr/lib/python2.7/site-packages/msrestazure/azure_active_directory.py\", line 480, in set_token\n    raise_with_traceback(AuthenticationError, \"\", err)\n  File \"/usr/lib/python2.7/site-packages/msrest/exceptions.py\", line 48, in raise_with_traceback\n    raise error\nmsrest.exceptions.AuthenticationError: , InvalidClientIdError: (invalid_request) AADSTS90002: Tenant xxxx not found. This may happen if there are no active subscriptions for the tenant. Check with your subscription administrator.\r\nTrace ID: xx-xx-x-xx-xx\r\nCorrelation ID: xx-xx-xx-xx-xx\r\nTimestamp: 2018-10-18 00:32:22Z\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}```

I hid some information by replacing it with xxxx.

```pip freeze
adal==1.1.0
ansible==2.7.0
applicationinsights==0.11.7
argcomplete==1.9.4
asn1crypto==0.24.0
azure-cli-core==2.0.35
azure-cli-nspkg==3.0.2
azure-common==1.1.11
azure-graphrbac==0.40.0
azure-keyvault==1.0.0a1
azure-mgmt-batch==4.1.0
azure-mgmt-compute==2.1.0
azure-mgmt-containerinstance==0.4.0
azure-mgmt-containerregistry==2.0.0
azure-mgmt-containerservice==3.0.1
azure-mgmt-dns==1.2.0
azure-mgmt-keyvault==0.40.0
azure-mgmt-marketplaceordering==0.1.0
azure-mgmt-monitor==0.5.2
azure-mgmt-network==1.7.1
azure-mgmt-nspkg==2.0.0
azure-mgmt-rdbms==1.2.0
azure-mgmt-resource==1.2.2
azure-mgmt-sql==0.7.1
azure-mgmt-storage==1.5.0
azure-mgmt-trafficmanager==0.50.0
azure-mgmt-web==0.32.0
azure-nspkg==2.0.0
azure-storage==0.35.1
bcrypt==3.1.4
certifi==2018.10.15
cffi==1.11.5
chardet==3.0.4
colorama==0.4.0
configparser==3.5.0
cryptography==2.3.1
entrypoints==0.2.3
enum34==1.1.6
humanfriendly==4.16.1
idna==2.7
iniparse==0.4
ipaddress==1.0.22
isodate==0.6.0
Jinja2==2.10
jmespath==0.9.3
keyring==15.1.0
kitchen==1.1.1
knack==0.3.3
MarkupSafe==1.0
monotonic==1.5
msrest==0.4.29
msrestazure==0.4.31
oauthlib==2.1.0
packaging==18.0
paramiko==2.4.2
pyasn1==0.4.4
pycparser==2.19
pycurl==7.19.0
Pygments==2.2.0
pygobject==3.22.0
pygpgme==0.3
PyJWT==1.6.4
pyliblzma==0.5.3
PyNaCl==1.3.0
pyOpenSSL==18.0.0
pyparsing==2.2.2
python-dateutil==2.7.3
pyxattr==0.5.1
PyYAML==3.13
requests==2.19.1
requests-oauthlib==1.0.0
SecretStorage==2.3.1
six==1.11.0
tabulate==0.8.2
urlgrabber==3.10
urllib3==1.23
yum-metadata-parser==1.1.4```

**Comment by abelgana** [comment]
I am not sure if it's related to this:
https://github.com/Azure/azure-sdk-for-python/issues/1629

**Comment by yungezz** [comment]
@abelgana  have you grant vault permission to your service principal when creating the vault?  Example playbook:  https://github.com/ansible/ansible/blob/devel/test/integration/targets/azure_rm_keyvault/tasks/main.yml#L30-L32

**Comment by abelgana** [comment]
I am not sure if it's implementation issue:

```
                authcredential = ServicePrincipalCredentials(
                client_id=self.credentials['client_id'],
                secret=self.credentials['secret'],
                tenant=tenant,
                resource="https://vault.azure.net")
```

this is from azure_rm_keyvaultsecret.py

I added this to the code:

```
from msrestazure.azure_cloud import AZURE_CHINA_CLOUD, AZURE_PUBLIC_CLOUD
            authcredential = ServicePrincipalCredentials(
                client_id=self.credentials['client_id'],
                secret=self.credentials['secret'],
                tenant=tenant,
                cloud_environment=AZURE_CHINA_CLOUD,
                resource="https://vault.azure.cn")
```

**Comment by yungezz** [comment]
great! thanks for the fixing, would you like to contribute a PR?

**Comment by Fred-sun** [comment]
@yungezz Could you help recheck this issue? How to deal with this issue? Thanks！

**Comment by Fred-sun** [comment]
@yungezz

**Comment by yungezz** [comment]
the issue was fixed in upstream repo, and will backport to role.
