### ISSUE TITLE
Microsoft.RecoveryServices/vaults/backupPolicies powershell timezone issue

### ISSUE THREAD

**Issue by jontreynes** [Azure/azure_preview_modules#149]
I am trying to create a new policy via powershell based off an existing policy already in a recovery vault.
When I do so, I use New-AzureRmRecoveryServicesBackupProtectionPolicy.
This command successfully creates a new policy. However, when creating the policy it does not copy the timezone.

To be more explicit, here is a run through. As a result of this run through, you will see that the time zone is not copied.

This policy "PCI" was created through the portal
 
![image](https://user-images.githubusercontent.com/19974635/47863614-e4f65200-ddb4-11e8-81e6-5417e95375f0.png)

 
![image](https://user-images.githubusercontent.com/19974635/47863445-87620580-ddb4-11e8-8710-be43a897f25f.png)

 
![image](https://user-images.githubusercontent.com/19974635/47863390-66011980-ddb4-11e8-9e10-c5286264fe18.png)

![image](https://user-images.githubusercontent.com/19974635/47863571-ce4ffb00-ddb4-11e8-85f8-cf6e8ca003d1.png)

**Comment by jontreynes** [comment]
update: 


It appears that the new policy is UTC. The issue must be the frontend portal updating the timezone to UTC

![image](https://user-images.githubusercontent.com/19974635/47877782-f0a83f80-ddd9-11e8-924f-54c6926b9e5b.png)

**Comment by yuwzho** [comment]
Hi @jontreynes This repo contains Azure modules for automation tool [Ansible](https://www.ansible.com/), seems you report the issue in a wrong place. If you still no idea where to report an issue, the [docs related repo](https://github.com/Azure/azure-docs-powershell/issues) or [powershell repo](https://github.com/Azure/azure-powershell/issues) may be the right places.

**Comment by jontreynes** [comment]
thank you - added to powershell repo https://github.com/Azure/azure-powershell/issues/7750
