### ISSUE TITLE
Standard SSD managed storage account type crashes azure_rm_virtualmachine_facts module

### ISSUE THREAD

**Issue by mikebranstein** [Azure/azure_preview_modules#182]
## Summary 
Running this module against a resource group with a VM that has a managed data disk set to Standard SSD storage causes the module to throw an exception.

## Steps to Reproduce
- Create a new resource group, named "az-temp-rg"
- Create a virtual machine via the Azure portal, OS disk can be **Premium SSD**
- Add a managed Data Disk with Storage type of **Standard SSD**
- Execute module against the resource group (see below)

```yaml
- azure_rm_virtualmachine_facts:
  auth_source: msi
  resource_group: "az-temp-rg"
```

## Expected Output
I expect this to return a dict of vm facts

## Actual Output
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'storageAccountType'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/kizanAdmin/.ansible/tmp/ansible-tmp-1547598227.64-106764736031393/AnsiballZ_azure_rm_virtualmachine_facts.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/kizanAdmin/.ansible/tmp/ansible-tmp-1547598227.64-106764736031393/AnsiballZ_azure_rm_virtualmachine_facts.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/kizanAdmin/.ansible/tmp/ansible-tmp-1547598227.64-106764736031393/AnsiballZ_azure_rm_virtualmachine_facts.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_azure_rm_virtualmachine_facts_payload_XlsJGR/__main__.py\", line 370, in <module>\n    \n  File \"/tmp/ansible_azure_rm_virtualmachine_facts_payload_XlsJGR/__main__.py\", line 366, in main\n    \n  File \"/tmp/ansible_azure_rm_virtualmachine_facts_payload_XlsJGR/__main__.py\", line 229, in __init__\n    \n  File \"/tmp/ansible_azure_rm_virtualmachine_facts_payload_XlsJGR/ansible_azure_rm_virtualmachine_facts_payload.zip/ansible/module_utils/azure_rm_common.py\", line 310, in __init__\n  File \"/tmp/ansible_azure_rm_virtualmachine_facts_payload_XlsJGR/__main__.py\", line 241, in exec_module\n    \n  File \"/tmp/ansible_azure_rm_virtualmachine_facts_payload_XlsJGR/__main__.py\", line 270, in list_items\n    \n  File \"/tmp/ansible_azure_rm_virtualmachine_facts_payload_XlsJGR/__main__.py\", line 352, in serialize_vm\n    \nKeyError: 'storageAccountType'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

## Additional Notes
If you follow the steps to reproduce, changing the VM data disk to managed Premium SSD storage, the module does not crash. I believe this is a wide-spread issue, as Standard SSD storage is not supported in various modules. 

Standard SSD storage went GA on 4 June 2018 (see https://azure.microsoft.com/en-us/blog/preview-standard-ssd-disks-for-azure-virtual-machine-workloads/). 

I believe other issues in the ansible/ansible (like https://github.com/ansible/ansible/issues/39958#issuecomment-454608644) may be related, as the error is similar. I'll note this post in ansible/ansible to tie these reports together.

**Comment by Fred-sun** [comment]
@zikalino Could you help take a look this issue? It seem relation with new add Standard SSD data disk. Thanks!

**Comment by Fred-sun** [comment]
@zikalino

**Comment by Fred-sun** [comment]
@zikalino

**Comment by Fred-sun** [comment]
@mikebranstein Thanks for your reporting!  It has been fixed by devel ansible. You can upgrade your ansibible to try (sudo pip install git+https://github.com/ansible/ansible.git@devel)! Thanks!

**Comment by Fred-sun** [comment]
can be closed, devel ver test success!

**Comment by yuwzho** [comment]
Fixed by https://github.com/ansible/ansible/pull/52540
