### ISSUE TITLE
Please enable tags support on azure_rm_sqldatabase

### ISSUE THREAD

**Issue by rdtechie** [Azure/azure_preview_modules#193]
Please enable tags support on the module azure_rm_sqldatabase.

**Comment by Fred-sun** [comment]
@zikalino Could you help take a look this issue when you're avaliable? Thanks!

**Comment by mvdpoel** [comment]
+1

**Comment by zikalino** [comment]
@rdtechie @mvdpoel 
just created a pr for this here, so once it's merged it should be propagated into azure_preview_modules soon:

https://github.com/ansible/ansible/pull/52615

**Comment by yuwzho** [comment]
As the PR is merged, close this one. Try it with latest upstream, and it should be in the azure_preview_module and azure_modules soon.
Please feel free to reopen it if there is  any problem.

**Comment by rdtechie** [comment]
Thanks guys! Much appreciated!

**Comment by zikalino** [comment]
@rdtechie no problem :-) what else can we do for you?
