### ISSUE TITLE
custom_data

### ISSUE THREAD

**Issue by tacobayle** [Azure/azure_preview_modules#195]
Is that possible to get custom_data with VMSS like it is with VM?

Thanks,
Nicolas

**Comment by Fred-sun** [comment]
@zikalino This is new feature for azure_rm_virutalmachine_scaleset modules? Could you help take a look this when you're available? Thanks!

**Comment by zikalino** [comment]
@tacobayle yes, I have implemented it and it will be available in Ansible 2.8 (or in preview modules)

https://github.com/ansible/ansible/pull/51380

pls let me know if it works for you

**Comment by Fred-sun** [comment]
@tacobayle Are you still here? Could you give a try according by the zikalino's comment? I have tested and get success result. Thanks!

**Comment by tacobayle** [comment]
@zikalino : many thanks.

@Fred-sun sorry I was abroad. Give me a couple of days and I will give it a try.

I am running:
avi@ansible:~$ ansible --version
ansible 2.8.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/avi/.ansible/plugins/modules', u'/usr/share/ansible/plugin                                                                        s/modules']
  ansible python module location = /home/avi/.local/lib/python2.7/site-packages/ansible
  executable location = /home/avi/.local/bin/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]

Should I upgrade or not?

Thanks

**Comment by Fred-sun** [comment]
@tacobayle Thanks! You need upgrade when you tested!

**Comment by Fred-sun** [comment]
@tacobayle Do you have a try? Please share you test result in here! Thanks!

**Comment by zikalino** [comment]
i am closing this issue, please reopen if there's any further problem.
