### ISSUE TITLE
Error in azure_rm_storageaccount module

### ISSUE THREAD

**Issue by rdtechie** [Azure/azure_preview_modules#196]
When trying to create a storage account with the latest preview module, I'm receiving this error:

```
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 113, in <module>
  File "<stdin>", line 105, in _ansiballz_main
  File "<stdin>", line 48, in invoke_module
  File "/tmp/ansible_azure_rm_storageaccount_payload_hLoWj8/__main__.py", line 589, in <module>
    
  File "/tmp/ansible_azure_rm_storageaccount_payload_hLoWj8/__main__.py", line 585, in main
    
  File "/tmp/ansible_azure_rm_storageaccount_payload_hLoWj8/__main__.py", line 282, in __init__
    
  File "/tmp/ansible_azure_rm_storageaccount_payload_hLoWj8/ansible_azure_rm_storageaccount_payload.zip/ansible/module_utils/azure_rm_common.py", line 310, in __init__
  File "/tmp/ansible_azure_rm_storageaccount_payload_hLoWj8/__main__.py", line 304, in exec_module
    
  File "/tmp/ansible_azure_rm_storageaccount_payload_hLoWj8/__main__.py", line 346, in get_account
    
AttributeError: 'StorageManagementClient' object has no attribute 'blob_services'

failed: [localhost] (item=noeus03devsasimp01) => {
    "changed": false, 
    "item": {
        "storage_account_name": "noeus03devsasimp01", 
        "storage_account_resource_group_name": "NoEu-S03-Dev-Rsg-Simp-01"
    }, 
    "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 113, in <module>\n  File \"<stdin>\", line 105, in _ansiballz_main\n  File \"<stdin>\", line 48, in invoke_module\n  File \"/tmp/ansible_azure_rm_storageaccount_payload_hLoWj8/__main__.py\", line 589, in <module>\n    \n  File \"/tmp/ansible_azure_rm_storageaccount_payload_hLoWj8/__main__.py\", line 585, in main\n    \n  File \"/tmp/ansible_azure_rm_storageaccount_payload_hLoWj8/__main__.py\", line 282, in __init__\n    \n  File \"/tmp/ansible_azure_rm_storageaccount_payload_hLoWj8/ansible_azure_rm_storageaccount_payload.zip/ansible/module_utils/azure_rm_common.py\", line 310, in __init__\n  File \"/tmp/ansible_azure_rm_storageaccount_payload_hLoWj8/__main__.py\", line 304, in exec_module\n    \n  File \"/tmp/ansible_azure_rm_storageaccount_payload_hLoWj8/__main__.py\", line 346, in get_account\n    \nAttributeError: 'StorageManagementClient' object has no attribute 'blob_services'\n",
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}
```

**Comment by rdtechie** [comment]
Anybody?

**Comment by Fred-sun** [comment]
@rdtechie Thanks for your reprot this issue！
@zikalino Could you help take a look this when you're avaliable? Thanks!

**Comment by yuwzho** [comment]
@rdtechie I think your Azure SDK version is out of date. The storageaccount is now supporting CORS management, which requires [`azure-mgmt-storage==3.1.0`](https://github.com/Azure/azure_preview_modules/blob/63430129d99113e6dff50dcc2823ba67091e4aa0/files/requirements-azure.txt#L24).

**Comment by rdtechie** [comment]
Hi @yuwzho , I checked, I have that particular version installed:
![image](https://user-images.githubusercontent.com/6579452/53148685-d32afb80-35ab-11e9-8055-a659617d23a2.png)

**Comment by rdtechie** [comment]
Hmm, not sure if something changed in the Azure SDK modules, but I've setup a new virtualenv. In that virtualenv I've installed the latest Ansible devel edition. After that I installed the latest Azure.azure_preview_modules from Ansible Galaxy. And then I installed the required Azure Python SDK packages as specified in https://github.com/Azure/azure_preview_modules/blob/master/files/requirements-azure.txt

My playbooks don't fail anymore on that APIVersion error message anymore. So for now the issue for me is solved, but maybe interesting for you guys to find the root cause of this? Anyway, if you want to close the issue I'll leave it to you.

**Comment by yuwzho** [comment]
The devel branch works because the [CORS support](https://github.com/ansible/ansible/commit/664e6fb9c8b2144a689a6026e2349c8d152c0530#diff-2b622fe76a39bb9004ac394693b03853R794)  is added to the devel branch. 

I think the problem is because the load error for `azure_rm_common` file. It calls for `apiVersion=2017-10-01` in [v2.7.7](https://github.com/ansible/ansible/commit/664e6fb9c8b2144a689a6026e2349c8d152c0530#diff-2b622fe76a39bb9004ac394693b03853L793). Then reaches [this error](https://github.com/Azure/azure-sdk-for-python/pull/3712/files#diff-0ad15ed56bf7ed6e586be0bc1852e827R172)
