### ISSUE TITLE
Create release for Ansible Role

### ISSUE THREAD

**Issue by mathieuherbert** [Azure/azure_preview_modules#199]
Hi,
Is it possible to create a release ? It would help to manage this role in ansible requirements file. As of now we can only reference master branch and always take the latest version.

**Comment by Fred-sun** [comment]
@yuwzho Can you help answer contributors' questions?  Thanks!

**Comment by yuwzho** [comment]
Hi @mathieuherbert , could you please explain more about the 'release'? We currently host the role in [Ansible Galaxy hub](https://galaxy.ansible.com/azure/azure_preview_modules). You can use ansible-galaxy command to install it. However there may be some un-compatible in Azure SDK version, so we provide another [pip requirement](https://github.com/Azure/azure_preview_modules/blob/master/files/requirements-azure.txt) to specify the SDK version.

**Comment by mathieuherbert** [comment]
Hi, @yuwzho when we want to use the Ansible module we provide
```
- src: azure.azure_preview_modules
```
it means we will always take the latest version. If there is any breaking change we will take it automatically. 
For example in the h[docker ansible](https://galaxy.ansible.com/geerlingguy/docker) we can see there are many vesions (latest one is the 2.5.2). We can fix this version in the ansible requirement file
```
- src: geerlingguy.docker
  version: 2.5.2
```
To make it possible the repository owner create a [git tag ](https://github.com/geerlingguy/ansible-role-docker/tree/2.5.2)

**Comment by yuwzho** [comment]
Thank you @mathieuherbert for the advise. We will add release for our role

**Comment by rdtechie** [comment]
And as a addition to the release tag, would it be cumbersome for you guys also to include the specific Ansible commit that was working with the release tag? For example, if you would now create release 0.1.0, then is would also be nice to add that that release is working with Ansible release https://github.com/ansible/ansible/releases/tag/v2.7.8 ?

Not sure if you would be able to add this in the documentation somewhere, but it would help us for sure to have some kind of stable combination of two developer repositories.

This would also prevent us reporting issues like these: https://github.com/Azure/azure_preview_modules/issues/196 as where it works in a later version of Ansible 2.7.7. But this is just one example.

**Comment by rdtechie** [comment]
When will tags be set?

**Comment by Fred-sun** [comment]
@rdtechie After the official Release, it will update it in the comments. Thank you very much!

**Comment by Fred-sun** [comment]
@yuwzho When official release is released, Please update here! Thanks!

**Comment by Fred-sun** [comment]
@yuwzho How about the issue going ahead？ waiting the tags to be set!? Thanks!

**Comment by Fred-sun** [comment]
@yuwzho Could you help update more about the role? when is the release? Thanks!

**Comment by yuwzho** [comment]
Should be expected after Ansible v2.8 release and sync job between ansible and the preview module finished.

**Comment by yuwzho** [comment]
Add the version 2.8.0, which make the Ansible/ansible azure modules to be a real subset of the azure preview modules
