### ISSUE TITLE
Please enable tags support on azure_rm_keyvault

### ISSUE THREAD

**Issue by rdtechie** [Azure/azure_preview_modules#201]
It looks like that the module azure_preview_modules/library/azure_rm_keyvault.py does support Azure tags, but the parameter is missing.

**Comment by Fred-sun** [comment]
@rdtechie Thanks for your report this issue! Since the module azure_preview_modules/library/azure_rm_keyvault.py already supports tags parameters, why do you said the tags are missing?

**Comment by rdtechie** [comment]
Hi @fred-sun, I think it's my lack of knowledge about python. I was trying to find it on the docs page: https://docs.ansible.com/ansible/latest/modules/azure_rm_keyvault_module.html but the tags parameter wasn't there. So I tried to read the code and I saw tags in the code. So I understand that the tags parameter IS working on this module?

**Comment by Fred-sun** [comment]
@rdtechie Yes, I misunderstood your meaning. Ansible document needs to add tags attribute! Thank you very much!

**Comment by Fred-sun** [comment]
@yungezz Could you help take a look this issue? azure_rm_keyvault Missing tags attribution on the Ansible docs page! Thanks!

**Comment by Fred-sun** [comment]
@rdtechie The newly added feature may not be added to the latest docs page soon before there is no Release, but you can find the answer in the devel docs page (https://docs.ansible.com/ansible/devel/modules/azure_rm_keyvault_module.html?highlight=azure_rm_keyvault). Thanks!

**Comment by rdtechie** [comment]
Thanks @fred-sun!

**Comment by yungezz** [comment]
@rdtechie I just checked and tested that tags in azure_rm_keyvault works as expected.

**Comment by rdtechie** [comment]
Thanks @yungezz ! I also saw it indeed. Thanks for the effort!
