### ISSUE TITLE
How does the development process looks like for the modules?

### ISSUE THREAD

**Issue by rdtechie** [Azure/azure_preview_modules#202]
Hi folks, I would like to have some more insight into the development process of these modules, as this will help to decide when to use which modules. As I understand till now it's as following:

1. Latest updates are always in `https://github.com/Azure/azure_preview_modules`.
2. One time per week (on wednesday) this repo gets integrated into Ansible devel.
3. Fixes/changes on Ansible devel for these modules get developed in the repo `https://github.com/Azure/azure_modules`

If my assumption is right, then the fixes/changes to `https://github.com/Azure/azure_preview_modules` gets merged back into `https://github.com/Azure/azure_preview_modules`?

If not, then I'm a bit lost. Can one of the devs explain me the process?

**Comment by Fred-sun** [comment]
@yuwzho Could you please help to reply to this process?

**Comment by yuwzho** [comment]
`azure_preview_modules` is a preview one where to place bits will not be merged to upstream immediately. We encourage contributor submit PR to the `azure_preview_modules` when sending PR to `ansible` upstream, once the PR to `azure_preview_modules`  merged, everyone can try the code with the role.  
Every week, we will cherry-pick all the changes in `ansible` upstream to the `azure_preview_modules` and will not cover the specific changes make to this repo.  
We also merge changes from `ansible` repo to `azure_modules` every Wednesday, which should be keep consistent with ansible's devel branch.

So when you wanna contribute to Ansible, we recommend you send PR to both upstream and this `azure_preview_modules` repo.

**Comment by yungezz** [comment]
from user's perspective, as you aware of, `azure_preview_modules` contains latest code for azure modules, because upstream `ansible` repo's PR merging process is controlled by community and normally longer. So new bugfixing/features/modules from microsoft in azure_modules will go to `azure_preview_modules` firstly. For community contribution in upstream, we have way to pull it back from upstream to preview module as @yuwzho mentioned.

**Comment by yuwzho** [comment]
Please feel free to contact us if you have feather question
