### ISSUE TITLE
Add vnet-subnet-id options to AKS Ansible module azure_rm_aks

### ISSUE THREAD

**Issue by sNathan13** [Azure/azure_preview_modules#204]
I am currently working on deploying an AKS cluster that is only accessible within the company. I am planning to automate the cluster creation using Ansible module azure_rm_aks. Would it be possible to add options for specifying vnet-id? If it is possible to add these options in the existing module, are there any docs that I could refer to?

**Comment by Fred-sun** [comment]
@zikalino @zikalino Could you help take a look this issue when you're available? There is missing vnet_subnet_id parameter for azure_rm_aks module! Thanks!

**Comment by yuwzho** [comment]
https://github.com/ansible/ansible/pull/51014

**Comment by Fred-sun** [comment]
@yuwzho It seem there is no vnet_subnet_id attribute in the latest Ansible and PR [#51014](https://github.com/ansible/ansible/pull/51014)! Could you help take a look? Thanks!
```e.g.
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (azure_rm_aks) module: vnet_subnet_id Supported parameters include: aad_profile, ad_user, addon, adfs_authority_url, agent_pool_profiles, api_profile, append_tags, auth_source, cert_validation_mode, client_id, cloud_environment, dns_prefix, enable_rbac, kubernetes_version, linux_profile, location, name, network_profile, password, profile, resource_group, secret, service_principal, state, subscription_id, tags, tenant"}
```

**Comment by yuwzho** [comment]
It should be a sub option under `agent_pool_profiles`

https://github.com/ansible/ansible/blob/acf3e73250c4a1f1e0d193e5aecb748e34057c56/lib/ansible/modules/cloud/azure/azure_rm_aks.py#L411

**Comment by Fred-sun** [comment]
@sNathan13 Are you still here? Could you give a try according by the above comments? the vnet_subnet_id is a sub option under agent_pool_profiles. Thanks!

**Comment by sNathan13** [comment]
Hi @Fred-sun , specifying subnet id works.. Thanks for all the efforts to make this happen.

**Comment by imlight** [comment]
Why below document link is not updated with above information. 

https://docs.ansible.com/ansible/latest/modules/azure_rm_aks_module.html#azure-rm-aks-module

I dont see  vnet_subnet_id in the document link

**Comment by Fred-sun** [comment]
> Why below document link is not updated with above information.
> https://docs.ansible.com/ansible/latest/modules/azure_rm_aks_module.html#azure-rm-aks-module
> I dont see  vnet_subnet_id in the document link

@imlight It has been added to the development version, you can see in the link (https://docs.ansible.com/ansible/devel/modules/azure_rm_aks_module.html#azure-rm-aks-module). Thank you very much!

**Comment by venkatredhat** [comment]
@imlight , I was trying to check the development version link which you have shared seems to removed. Could you please help me with the updated link where I could find the relevant information.
https://docs.ansible.com/ansible/devel/modules/azure_rm_aks_module.html#azure-rm-aks-module
