### ISSUE TITLE
Add aadProfile parameters to azure_rm_aks module

### ISSUE THREAD

**Issue by sNathan13** [Azure/azure_preview_modules#210]
Hi,

Would it be possible to add a functionality to specify the parameters for aadProfile? This would enable deploying an AKS cluster with Azure AD integration.

Thanks!

**Comment by Fred-sun** [comment]
@yuwzho @zikalino It seem new feature for azure_rm_aks modules, but I cannot find the introduction of this feature, please help to check when you are free, do we need to add this feature? Thanks!

**Comment by yuwzho** [comment]
https://github.com/ansible/ansible/pull/51014

**Comment by Fred-sun** [comment]
@sNathan13 Are you still here? Could you give a try according by yuwzho's comments? Thanks!

**Comment by sNathan13** [comment]
@Fred-sun I will give it a try soon. Thanks for helping out.

**Comment by Fred-sun** [comment]
@sNathan13 Have you finished the test? Please update the test results here？ Thanks!

**Comment by sNathan13** [comment]
Hi @Fred-sun, sorry for the delayed response. I was able to deploy with aadProfile parameters. Thank you :)
