### ISSUE TITLE
SDK defaults to api_version 2014-04-01

### ISSUE THREAD

**Issue by mvdpoel** [Azure/azure_preview_modules#214]
Hi,

Currently i'm working with the azure_rm_sqldatabase module.

Somehow it always defaults back to api_version=2014-04-01

I've tried adding the module parameter api_version: 'latest' which also results in version 2014-04-01

I've also tried naming it explicitly api_version: '2017-10-01-preview' which results to: 'unknown Azure API profile: 2017-10-01-preview'"}

Also tried: api_version: '2017-10-01' which results in 'unknown Azure API profile: 2017-10-01'

Looking at: https://docs.microsoft.com/en-us/rest/api/sql/databases/createorupdate

'2017-10-01-preview' should be the latest. Which is kind of a problem since the structure has changed slightly.

Am i trying with incorrect parameter values? 
Why is latest 2014-04-01 and not 2017-10-01?
Any workaround available to force version 2017?

Please help

Thanks!

**Comment by Fred-sun** [comment]
@yungezz Please help take a look this issue when you're available! Thanks!

**Comment by yungezz** [comment]
hi @zikalino   could you pls look at the issue?

**Comment by Fred-sun** [comment]
@zikalino Please help take a look this issue when you're available! Thanks!

**Comment by Fred-sun** [comment]
@zikalino

**Comment by Fred-sun** [comment]
@zikalino Please take a look this issue! Thanks!

**Comment by Fred-sun** [comment]
@zikalino

**Comment by MyronFanQiu** [comment]
@mvdpoel Thanks for reporting this issue! Now I am investigating this issue and need your help. Can you check the version of the python sql sdk on your machine by tapping the command ```pip list | grep azure-mgmt-sql``` ? Thanks!

**Comment by Fred-sun** [comment]
@mvdpoel Are you still here? Could you can reply the above comments? Thanks a lot!

**Comment by MyronFanQiu** [comment]
@mvdpoel Hi~ I first list the possible reason in case I forget it. 

- Due to the dependency sdk, the sqldatabase module doesn't support different api_version. 
- For your need, now, the sqldatabase module do use the "2017-10-01-preview" api_version.
- About the November, 2018, there is a upgrade for the version of the dependency sdk. The dependency sdk used before November, 2018 indeed choose the "2014-04-01" api_version.

So, If the version of sql sdk in your machine is 0.7.1 or older, you can run the comman 
`pip install -r ~/.ansible/roles/azure.azure_preview_modules/files/requirements-azure.txt` 
to upgrade the sdk and the problem should be solved.

If the version of sql sdk in your machine is newer than 0.7.1, please let me know and we can continue solving this issue.

**Comment by Fred-sun** [comment]
@mvdpoel Could you give me a try the suggestions in the comments above? Thanks a lot!

**Comment by Fred-sun** [comment]
kindly ping

**Comment by Fred-sun** [comment]
@mvdpoel Are you still here? Could you can a feedback according by the comments? Thanks a lot!

**Comment by mvdpoel** [comment]
Thx, but not working that module anymore :)

**Comment by Fred-sun** [comment]
> @mvdpoel Hi~ I first list the possible reason in case I forget it.
> 
> Due to the dependency sdk, the sqldatabase module doesn't support different api_version.
> For your need, now, the sqldatabase module do use the "2017-10-01-preview" api_version.
> About the November, 2018, there is a upgrade for the version of the dependency sdk. The dependency sdk used before November, 2018 indeed choose the "2014-04-01" api_version.
> 
> So, If the version of sql sdk in your machine is 0.7.1 or older, you can run the comman
> pip install -r ~/.ansible/roles/azure.azure_preview_modules/files/requirements-azure.txt
> to upgrade the sdk and the problem should be solved.
> If the version of sql sdk in your machine is newer than 0.7.1, please let me know and we can continue solving this issue.

@MyronFanQiu Contributors are no longer paying attention to this module, and the new version of the SDK doesn't have this problem. Can we turn it off and reopen it when we encounter new problems? Please check! Thank you very much!

**Comment by MyronFanQiu** [comment]
@Fred-sun Thanks. @mvdpoel  I am going to close this issue. If you need, please feel free to reopen it.
