### ISSUE TITLE
ImportError: No module named monitor.version

### ISSUE THREAD

**Issue by Tomelin** [Azure/azure_preview_modules#218]
Hi dear,

My playbook azure, be this error:

The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_azure_rm_subnet_payload_beyNLU/ansible_azure_rm_subnet_payload.zip/ansible/module_utils/azure_rm_common.py", line 147, in <module>
    from azure.mgmt.monitor.version import VERSION as monitor_client_version
ImportError: No module named monitor.version
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "ad_user": null, 
            "address_prefix_cidr": "10.4.0.0/22", 
            "adfs_authority_url": null, 
            "api_profile": "latest", 
            "append_tags": true, 
            "auth_source": null, 
            "cert_validation_mode": null, 
            "client_id": null, 
            "cloud_environment": "AzureCloud", 
   …

Whats problem?
I installed ansible[azure], azure-mgmt-monitor ,....

**Comment by Fred-sun** [comment]
@Tomelin Thanks for your report this issue！Could you help share your test YML and "pip list " info, I will try.  Thanks!

**Comment by yuwzho** [comment]
@Tomelin From Ansible v2.7 we added the autoscale module which requires the monitor library. If you install the module role based on an Ansible version < 2.7, you may need to re-install the Azure SDK dependency as this [requirement.txt](https://github.com/Azure/azure_preview_modules/blob/master/files/requirements-azure.txt).

*BTW, we always encourage user re-install the Azure dependency when using this module role.*

**Comment by Tomelin** [comment]
@yuwzho Thanks,

My ansible is v.2.7.7  `ansible --version   ansible 2.7.8`.

The azure-mgmt-monitor be installed.

`/var/lib/awx/venv/awx/bin/pip freeze  | grep azure-mgmt-monitor`
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
azure-mgmt-monitor==0.5.2


Is not need re-install dependency in requirements.txt, correct?

**Comment by yuwzho** [comment]
Seems you run into a problem that your pip installs the Azure libraries into different folders. You can refer [this page](https://github.com/VSChina/ansible/wiki/1-FAQ:-Do-you-have-azure-=2.0.0-installed%3F-No-module-named-XXX) to do a check and fix.

**Comment by Fred-sun** [comment]
@Tomelin Are you still here? Could you can give a try according by the above comments? Thanks!

**Comment by Tomelin** [comment]
Hi dear,

I used Ansibe tower and my problem is resolved.

I have need execute is:

/var/lib/awx/venv/ansible/bin/pip install --upgrade azure-mgmt-network
/var/lib/awx/venv/ansible/bin/pip install --upgrade azure-mgmt-compute

My problem is resolved

Thanks!!
