### ISSUE TITLE
Feature Request: Application Security Groups in NSG Port Rules

### ISSUE THREAD

**Issue by rdtechie** [Azure/azure_preview_modules#222]
There's a new module for creating Application Security Groups, and the Network Interface Module also supports ASG tags.

But the one missing piece is that on this moment the modules azure_rm_securitygroup.py doesn't support ASG's in NSG Port Rules. 

Can you please add the support for it? Maybe a suggestion to add two dictionary parameters, `source_application_security_groups` & `destination_application_security_groups` Both support list items (in which the ID can be put to the ASG) or a dict with two properties: name & resource_group.

I also mentioned this here: https://github.com/ansible/ansible/issues/43802 but I feel that this repository is a better place to put this issue.

**Comment by Fred-sun** [comment]
@yungezz Please help take a look this issue? new feature( destination_application_security_group)  for ASG's module! Thanks!

**Comment by yungezz** [comment]
@rdtechie  thanks for the info, we're looking at it.

**Comment by rdtechie** [comment]
Anytime @yungezz , let me know if I can help you testing it; I'm currently working in a environment where this functionality is needed, so I can test it as soon you have something ready.

**Comment by rdtechie** [comment]
@yuwzho Can you already tell me something about the possible implementation date?

**Comment by yuwzho** [comment]
@yungezz

**Comment by yungezz** [comment]
@rdtechie estimation by end of this week. There's some backward compatibility behavior need to be considered.

**Comment by yungezz** [comment]
PR ready,  pls see reference. Pls have a try and let me know any issue.

**Comment by yungezz** [comment]
PR merged. close this one for now. feel free  to open it if met any problem.

**Comment by rdtechie** [comment]
@yungezz I'm sorry for not giving feedback. This seems to work perfectly! Thanks for the quick solution.
