### ISSUE TITLE
azure_rm_virtualmachine > accept_terms > error not handled

### ISSUE THREAD

**Issue by nergalex** [Azure/azure_preview_modules#233]
Hi,
I encounter this error when I set "accept terms" for an image that does not need to. Maybe this error can be handled for a cosmetic point of view.

### SYMPTOM
{
    "_ansible_parsed": false,
    "exception": "Traceback (most recent call last):\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1554152497.12-261253049497350/AnsiballZ_azure_rm_virtualmachine.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1554152497.12-261253049497350/AnsiballZ_azure_rm_virtualmachine.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1554152497.12-261253049497350/AnsiballZ_azure_rm_virtualmachine.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_azure_rm_virtualmachine_payload_u26OpA/__main__.py\", line 1950, in <module>\n  File \"/tmp/ansible_azure_rm_virtualmachine_payload_u26OpA/__main__.py\", line 1946, in main\n  File \"/tmp/ansible_azure_rm_virtualmachine_payload_u26OpA/__main__.py\", line 809, in __init__\n  File \"/tmp/ansible_azure_rm_virtualmachine_payload_u26OpA/ansible_azure_rm_virtualmachine_payload.zip/ansible/module_utils/azure_rm_common.py\", line 324, in __init__\n  File \"/tmp/ansible_azure_rm_virtualmachine_payload_u26OpA/__main__.py\", line 1196, in exec_module\nAttributeError: 'NoneType' object has no attribute 'get'\n",
    "_ansible_no_log": false,
    "_ansible_delegated_vars": {
        "ansible_delegated_host": "localhost",
        "ansible_host": "localhost"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1554152497.12-261253049497350/AnsiballZ_azure_rm_virtualmachine.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1554152497.12-261253049497350/AnsiballZ_azure_rm_virtualmachine.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1554152497.12-261253049497350/AnsiballZ_azure_rm_virtualmachine.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_azure_rm_virtualmachine_payload_u26OpA/__main__.py\", line 1950, in <module>\n  File \"/tmp/ansible_azure_rm_virtualmachine_payload_u26OpA/__main__.py\", line 1946, in main\n  File \"/tmp/ansible_azure_rm_virtualmachine_payload_u26OpA/__main__.py\", line 809, in __init__\n  File \"/tmp/ansible_azure_rm_virtualmachine_payload_u26OpA/ansible_azure_rm_virtualmachine_payload.zip/ansible/module_utils/azure_rm_common.py\", line 324, in __init__\n  File \"/tmp/ansible_azure_rm_virtualmachine_payload_u26OpA/__main__.py\", line 1196, in exec_module\nAttributeError: 'NoneType' object has no attribute 'get'\n",
    "changed": false,
    "module_stdout": "",
    "rc": 1,
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"
}

### CONDITION
- name: Create VM
  delegate_to: localhost
  azure_rm_virtualmachine:
    resource_group: "rg-{{ extra_platform_name }}"
    name: "{{ extra_vm_name }}"
    location: "{{ extra_location }}"
    short_hostname: "{{ extra_vm_name }}"
    vm_size: "{{ app_vm_size }}"
    tags: "{{ extra_platform_tags }}
              Name={{ extra_vm_name }}
              owner={{ owner }}
              zone={{ extra_zone_name }}"
    admin_username: "{{ app_admin_username }}"
    ssh_password_enabled: false
    ssh_public_keys:
      - path: "/home/{{ app_admin_username }}/.ssh/authorized_keys"
        key_data: "{{ key_data }}"
    image:
      offer: CentOS
      publisher: OpenLogic
      sku: '7.5'
      version: latest
    managed_disk_type: Standard_LRS
    os_type: Linux
    network_interface_names:
      - "nic-{{ extra_platform_name }}-{{ extra_vm_name }}-management"
      - "nic-{{ extra_platform_name }}-{{ extra_vm_name }}-app"
    accept_terms: true

**Comment by Fred-sun** [comment]
@zikalino I meet same error when create VM attach with accept_terms. Please take a look when you're available! Thanks!

**Comment by Fred-sun** [comment]
@zikalino
