### ISSUE TITLE
azure_rm_deployment - error with "name" parameter

### ISSUE THREAD

**Issue by nergalex** [Azure/azure_preview_modules#236]
Hi,
In azure_rm_deployment module, when I use "name" parameter I get an error (see below). It's OK when using the alias "deployment_name"

`"msg": "Unsupported parameters for (azure_rm_virtualmachine) module: deployment_mode, parameters, template_link, wait_for_deployment_completion Supported parameters include: accept_terms, ad_user, adfs_authority_url, admin_password, admin_username, allocated, api_profile, append_tags, auth_source, availability_set, cert_validation_mode, client_id, cloud_environment, custom_data, data_disks, generalized, image, location, managed_disk_type, name, network_interface_names, open_ports, os_disk_caching, os_disk_name, os_disk_size_gb, os_type, password, plan, profile, public_ip_allocation_method, remove_on_absent, resource_group, restarted, secret, short_hostname, ssh_password_enabled, ssh_public_keys, started, state, storage_account_name, storage_blob_name, storage_container_name, subnet_name, subscription_id, tags, tenant, virtual_network_name, virtual_network_resource_group, vm_size, zones"`

**Comment by Fred-sun** [comment]
@nergalex  Thanks for your contribution, It seem relater with your parameters define error, not error with 'name' parameter! Could you help share your playbook? Thanks!

**Comment by nergalex** [comment]
Hi Fred-sun,
You can see below 2 tests results.

### Test 1. Playbook with 'name' paramater
- name: Delete Stack
  delegate_to: localhost
  azure_rm_deployment:
    resource_group: "rg-{{ extra_platform_name }}"
    name: "{{ extra_stack_name }}"
    state: absent

### Test 1. Error message in Ansible
Unsupported parameters for (azure_rm_deployment) module: name Supported parameters include: ad_user, adfs_authority_url, api_profile, append_tags, auth_source, cert_validation_mode, client_id, cloud_environment, deployment_mode, deployment_name, location, parameters, parameters_link, password, profile, resource_group_name, secret, state, subscription_id, tags, template, template_link, tenant, wait_for_deployment_completion, wait_for_deployment_polling_period

### Test 2. playbook with with 'deployment_name' paramater
- name: Delete Stack
  delegate_to: localhost
  azure_rm_deployment:
    resource_group: "rg-{{ extra_platform_name }}"
    deployment_name: "{{ extra_stack_name }}"
    state: absent

### Test 2. no error in Ansible

**Comment by Fred-sun** [comment]
@nergalex Thanks for your update. I try your playbook, Meet same error in Ansible( only support deployment_name). But if I used azure_preview_modules to test, test success, it support name and deployment_name).  Thanks!

**Comment by Fred-sun** [comment]
@zikalino Please help take a look this issue when you're available! Thanks!

**Comment by yuwzho** [comment]
Fred's testing result is an expected behavior. @nergalex , the Preview modules go faster than the ansible release. 

If you use the `name` in Ansible with version below 2.8 (will be released these days), it would fail as your error message. But the 2.8 will support this.

If you install the azure_preview_modules and use it as [this instruction](https://github.com/Azure/azure_preview_modules/blob/master/README.md) , you will get this work.
