### ISSUE TITLE
Azure_rm_managed_disks does not support availability zones

### ISSUE THREAD

**Issue by andyeff** [Azure/azure_preview_modules#238]
Hi all,

I've configured an Ansible Tower server to be able to use these preview modules to support a request to build VM's in availability zones. So far so good, however some of the servers need some data disks, and the managed_disks module doesn't support the zones parameter like the virtual_machine module does.

However ... I took a look at the main Ansible devel branch and noticed there is a manageddisks module that DOES support the parameter, so I'm sorta trying to get things working with that file ( https://raw.githubusercontent.com/ansible/ansible/devel/lib/ansible/modules/cloud/azure/azure_rm_manageddisk.py ) included in a library/ dir for my playbook.

Looks to be working! However I am a bit confused as I assumed this repo would have the latest / bleeding edge parameters available in the modules? Would someone be able to explain how this repos' azure modules, and the ones from Ansible development branch relate to each other? I was under the possibly-misguided assumption that if I spot something in the Ansible devel branch that I need, I should use the modules from this repo instead as it's easy to keep things up to date with ansible-galaxy that way.

**Comment by rdtechie** [comment]
@andyeff I've asked this question before and here's explanation on how it works: https://github.com/Azure/azure_preview_modules/issues/202

**Comment by andyeff** [comment]
Ah, many thanks @rdtechie :)
