### ISSUE TITLE
from azure.mgmt.rdbms.mariadb import MariaDBManagementClient

### ISSUE THREAD

**Issue by Tomelin** [Azure/azure_preview_modules#239]
Hi Dear,

This error be occurring in my playbook with Ansible Tower.  Whats lib is need install?

I installed  azure.mgmt.rdbms, but not success.

Whats problem?

"exception": "Traceback (most recent call last):\n  File \"/tmp/ansible_azure_rm_networkinterface_payload_nKUJGv/ansible_azure_rm_networkinterface_payload.zip/ansible/module_utils/azure_rm_common.py\", line 173, in <module>\n    from azure.mgmt.rdbms.mariadb import MariaDBManagementClient\nImportError: No module named mariadb\n",

**Comment by Fred-sun** [comment]
@Tomelin Thanks for your reporting! you can try this guide to solve you dependency problem--https://github.com/VSChina/ansible/wiki/1-FAQ:-Do-you-have-azure-=2.0.0-installed%3F-No-module-named-XXX , Please share your playbook, pip info and environment to let me try! Thanks!

**Comment by Fred-sun** [comment]
@Tomelin Can you provide more information for me to try??

**Comment by yuwzho** [comment]
@Tomelin What's the version do you installed? We have a [requirement file](https://github.com/Azure/azure_preview_modules/blob/master/files/requirements-azure.txt) in the files folder, you can download it and install by `pip install -r requirements.txt`

It says `azure-mgmt-rdbms` should in version `1.4.1`

**Comment by Tomelin** [comment]
Hi dear,

I update ansible[azure] in my server and resolved.

thanks.

**Comment by yuwzho** [comment]
good
