### ISSUE TITLE
azure_rm_virtualmachine >> diagnostics_profile supported ?

### ISSUE THREAD

**Issue by nergalex** [Azure/azure_preview_modules#249]
Hi,
Is it possible to set a 'diagnostics_profile' in the azure_rm_virtualmachine module ?
I am looking for equivalent parameters below as I used in Azure SDK :
```
            'diagnostics_profile': {
                'boot_diagnostics': {
                    'enabled': True,
                    'storage_uri': "Microsoft.Storage/storageAccounts/myDataStorageAccountName...",
                },
            },
```

**Comment by Fred-sun** [comment]
@nergalex Thanks for your contribution. This feature has been add by PR [#49661](https://github.com/ansible/ansible/pull/49661
), when the PR merged, will add to preview module! Thanks!

**Comment by nergalex** [comment]
OK thanks!

**Comment by yuwzho** [comment]
Close this one as the PR is merged to upstream, the change should go to this repo in tomorrow's sync
