### ISSUE TITLE
Public IP create fails with AttributeError: 'PublicIPAddress' object has no attribute 'ip_tags'

### ISSUE THREAD

**Issue by elvinasp** [Azure/azure_preview_modules#254]
while trying to create LoadBalancer resource in AzureStack Ansible run fails with the Python error. Ansible playbooks works perfectly against AzureCloud, however our target environment is AzureStack and we are using AzureCloud only for temporary development.

To be able to run I have had to patch azure_rm_common.py to have API version to match available API on our AzureStack environment. 

When using Ansible supplied Azure modules, I was getting error at next playbook step:
Creating LoadBalancer fails with __init__() takes exactly 1 argument (2 given) #253.

**Environment:**
OS: Ubuntu 18.04.1 LTS
Ansible: 
`ansible 2.7.9
  config file = None
  configured module search path = [u'/home/atlas-admin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]`
Azure preview modules installed as defined in <https://galaxy.ansible.com/Azure/azure_preview_modules>
AzureStack: 1.1901.0.95 

**Ansible snippet**
```yaml
- name: Create public IP
  azure_rm_publicipaddress:
    name: "{{ definedPiblicipaddress }}"
    resource_group: "{{ resourceGroup }}"
    allocation_method: Static
    domain_name:  "{{ resourceGroup }}"
    sku: Basic
```

**Python Error**
```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\nTraceback (most recent call last):\n  File \"/home/atlas-admin/.ansible/tmp/ansible-tmp-1556778849.87-147610747740374/AnsiballZ_azure_rm_publicipaddress.py\", line 261, in <module>\n    _ansiballz_main()\n  File \"/home/atlas-admin/.ansible/tmp/ansible-tmp-1556778849.87-147610747740374/AnsiballZ_azure_rm_publicipaddress.py\", line 251, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/atlas-admin/.ansible/tmp/ansible-tmp-1556778849.87-147610747740374/AnsiballZ_azure_rm_publicipaddress.py\", line 119, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_azure_rm_publicipaddress_payload_ak4rpr/__main__.py\", line 355, in <module>\n  File \"/tmp/ansible_azure_rm_publicipaddress_payload_ak4rpr/__main__.py\", line 351, in main\n  File \"/tmp/ansible_azure_rm_publicipaddress_payload_ak4rpr/__main__.py\", line 216, in __init__\n  File \"/tmp/ansible_azure_rm_publicipaddress_payload_ak4rpr/ansible_azure_rm_publicipaddress_payload.zip/ansible/module_utils/azure_rm_common.py\", line 347, in __init__\n  File \"/tmp/ansible_azure_rm_publicipaddress_payload_ak4rpr/__main__.py\", line 243, in exec_module\n  File \"/tmp/ansible_azure_rm_publicipaddress_payload_ak4rpr/__main__.py\", line 170, in pip_to_dict\nAttributeError: 'PublicIPAddress' object has no attribute 'ip_tags'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Azure azure_rm_common.py patch diff**
```diff
--- azure_rm_common.py.ORIG     2019-04-18 02:58:37.000000000 +0000
+++ azure_rm_common.py.NEW      2019-05-02 06:22:21.644381615 +0000
@@ -865,13 +865,13 @@
         if not self._network_client:
             self._network_client = self.get_mgmt_svc_client(NetworkManagementClient,
                                                             base_url=self._cloud_environment.endpoints.resource_manager,
-                                                            api_version='2018-08-01')
+                                                            api_version='2017-10-01')
         return self._network_client

     @property
     def network_models(self):
         self.log("Getting network models...")
-        return NetworkManagementClient.models("2018-08-01")
+        return NetworkManagementClient.models("2017-10-01")

     @property
     def rm_client(self):
@@ -893,13 +893,13 @@
         if not self._compute_client:
             self._compute_client = self.get_mgmt_svc_client(ComputeManagementClient,
                                                             base_url=self._cloud_environment.endpoints.resource_manager,
-                                                            api_version='2018-06-01')
+                                                            api_version='2017-12-01')
         return self._compute_client

     @property
     def compute_models(self):
         self.log("Getting compute models")
-        return ComputeManagementClient.models("2018-06-01")
+        return ComputeManagementClient.models("2017-12-01")

     @property
     def dns_client(self):
```

**Comment by yuwzho** [comment]
HI @elvinasp , currently we are target on the azure cloud. I am very sorry about the new option `ip_tags` is not supported yet in the azure stack. I create a branch without the `ip_tags` in https://github.com/Azure/azure_preview_modules/tree/pip-stack .You can have a test on it.

To use the specific branch, you need to 
1. Install this branch using `ansible-galaxy install git+https://github.com/Azure/azure_preview_modules,pip-stack`. 
2. In the playbook, refer `role: azure_preview_modules` rather than `role: azure.azure_preview_modules`.

**Comment by elvinasp** [comment]
> HI @elvinasp , currently we are target on the azure cloud. I am very sorry about the new option `ip_tags` is not supported yet in the azure stack. I create a branch without the `ip_tags` in https://github.com/Azure/azure_preview_modules/tree/pip-stack .You can have a test on it.
> 
Thanks. 

Branch works properly after I patch azure_rm_common.py with compatible API versions. But API version incompatibility is a different issue.

**Comment by elvinasp** [comment]
It looks like the same issue applies to azure_rm_publicipaddress_facts.py file. It also has ip_tags and AzureStack API chokes on those attributes.

**Comment by yuwzho** [comment]
HI @elvinasp I also remove the `ip_tags` in the specific branch, you can take a look.

As for long term solution, unfortunately, we don't have a plan to support Azure Stack these days. You can fork this repo and modified the API versions and remove the unsupported options, then host your own roles. 
The [azure-sdk-for-python](https://github.com/Azure/azure-sdk-for-python) can be a reference about the difference among different API versions.
