### ISSUE TITLE
Image Reference ID support in azure_rm_virtualmachine

### ISSUE THREAD

**Issue by rdtechie** [Azure/azure_preview_modules#257]
Now that the new service Shared Image Gallery is GA, I'd like to be able to consume those type of images in my code. Does the azure_rm_virtualmachine module supports Image Reference ID's like the az cli and PowerShell Az module does? 

Examples here: 
- https://docs.microsoft.com/en-us/azure/virtual-machines/windows/shared-images#create-vms-from-an-image
- https://docs.microsoft.com/en-us/azure/virtual-machines/linux/shared-images#create-a-vm

I've tried to use a reference id on the parameter `image`, like this:
```yaml
image: '/subscriptions/<our-subscription-id>/resourceGroups/<our-shared-image-gallery-rsg>/providers/Microsoft.Compute/galleries/<our-gallery-name>/images/rhel-7-cis/versions/1.0.1'
```
But this doesn't work.

**Comment by yuwzho** [comment]
Zim is working on it!

**Comment by rdtechie** [comment]
An addition, I also think then the azure_rm_virtualmachine_scaleset have to be updated?

**Comment by rdtechie** [comment]
Is there progress on this?

**Comment by zikalino** [comment]
@rdtechie I plan to finish shared image gallery implementation this week. and then I will make all necessary updates in the vm module.

**Comment by rdtechie** [comment]
Cool @zikalino ! Let me know, happy to test.

**Comment by Fred-sun** [comment]
@zikalino Could you please help to update how the problem is handled now? Thank you very much!

**Comment by rdtechie** [comment]
How is this one going?

**Comment by MyronFanQiu** [comment]
@rdtechie Zim is working on it. https://github.com/ansible/ansible/pull/57386

**Comment by rdtechie** [comment]
But I'm not seeing a reference in that PR to the functionality that I requested in this issue. Or will it be picked up once Zim finished the Shared Image Gallery modules?

**Comment by MyronFanQiu** [comment]
I think so. @zikalino am I right?

> @rdtechie I plan to finish shared image gallery implementation this week. and then I will make all necessary updates in the vm module.

**Comment by zikalino** [comment]
I am finally working on it right now, that's the last element

**Comment by rdtechie** [comment]
Do you have an update @zikalino ?

**Comment by MyronFanQiu** [comment]
@rdtechie https://github.com/ansible/ansible/pull/58106 It has been merged. And I have sync this repo (azure roles) just a few hours ago. https://github.com/Azure/azure_preview_modules/blob/b8caa5a27d8cbfa98035b7162dd77ad6f844f31b/library/azure_rm_virtualmachine.py#L513-L521

**Comment by zikalino** [comment]
@rdtechie yes, it's merged, I am also going to merge vmss equivalent very soon, the pr is pending

**Comment by rdtechie** [comment]
I've tested this and either I'm doing something wrong or it doesn't work yet. I am getting this error:
` "msg": "Error creating or updating virtual machine weeus03dlsimp01 - Azure Error: InvalidParameter\nMessage: The value of parameter imageReference.id is invalid.\nTarget: imageReference.id"`

The value that I'm using for the ID is this (I left out the subscription ID):
`'/subscriptions/<mysubscriptionid>/resourceGroups/WEEU-S01-PRD-RSG-ASIG-01/providers/Microsoft.Compute/galleries/weeus01prdasig01/images/rhel-7-cis/versions/1.0.1'`

**Comment by MyronFanQiu** [comment]
@zikalino @smile37773 Could you please take a look about this error?

**Comment by rdtechie** [comment]
Any update?

**Comment by MyronFanQiu** [comment]
@rdtechie Hello. I want to double confirm your feature request. Do you want to use a image id as a source for VM or use a image id in the image shared gallery? @smich73 test the feature by using image id `/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/myResourceGroup/providers/Microsoft.Compute/images/testimagea`. I'm not sure whether this meet your request or not?

**Comment by rdtechie** [comment]
Hi @MyronFanQiu, like I've explained in the start post, I want to be able to use images from a Shared Image Gallery. I've also included examples in the start post. And no, it doesn't meet the request; I've shown this in post https://github.com/Azure/azure_preview_modules/issues/257#issuecomment-507050276

**Comment by rdtechie** [comment]
Any update?

**Comment by rdtechie** [comment]
Any update?

**Comment by zikalino** [comment]
@rdtechie I have rechecked it and I can think of only possible cause of this failure, could you check if the image you have created has proper state? you can check it easily in the portal. if something went wrong it should be in "failed" state.

**Comment by rdtechie** [comment]
Hi, @zikalino & me had some contact in the background, and it appears that the module included in https://github.com/Azure/azure_modules is not working correctly. Zim pointed me to another module: https://github.com/microsoft/AnsibleLabs/blob/master/lab-07-shared-image-gallery/modules/library/azure_rm_virtualmachine.py and I've tried that one, and it works. When will the module get fixed in Ansible core or https://github.com/Azure/azure_modules ?

**Comment by rdtechie** [comment]
Anybody has an update, please???

**Comment by Fred-sun** [comment]
@zikalino

**Comment by Fred-sun** [comment]
@rdtechie PR is combined, will soon have to merge to preview module. Should have merged to https://github.com/Azure/azure_modules, please try again. Thank you!

**Comment by rdtechie** [comment]
Hi @Fred-sun , unfortunately I'm not at this customer anymore, but I will try it myself in a sandbox environment. Thanks!

**Comment by Fred-sun** [comment]
@rdtechie  After you try, please share the test results. Thank you very much!

**Comment by rwaal** [comment]
Hi @Fred-sun, 
Because @rdtechie no longer works for the particular customer (I still am) I took over. I tested using the preview modules, and it all seems to work correctly now. I was able to deploy a Virtual Machine using an image from the Shared Image Gallery. \
Many thanks for making this work! :smile:

**Comment by Fred-sun** [comment]
@rwaal Thanks for you testing. Please close this question if you can.

**Comment by rdtechie** [comment]
@Fred-sun I'll close it for @rwaal 

Thanks all!

**Comment by rewilliams1** [comment]
Hello guys, I am trying to use azure_rm_virtualmachine to deploy a vm from shared image gallery. I am able to deploy directly from Shared Image Gallery directly but when I try to run the task below I get the error message below.

`- name: Create FMOS VM
  azure_rm_virtualmachine:
    ad_user: "{{ ad_username }}"
    password: "{{ ad_password }}"
    resource_group: "{{ resource_group }}"
    name: "{{ db_server_name }}"
    vm_size: Standard_E4s_v3
    os_disk_caching: ReadWrite
    admin_username: {{ admin_username }}
    admin_password: "{{ admin_password }}"
    subnet_name: "{{ subnet_name }}"
    virtual_network_name: "{{ vnet_name }}"
    network_interface_names: "{{ db_network_interface }}"
    public_ip_allocation_method: Dynamic
    managed_disk_type: Standard_LRS
    image:
      id: /subscriptions/{{ subscription_id }}/resourceGroups/{{ resource_group }}/providers/Microsoft.Compute/galleries/{{ gallery_name }}/images/rhel-7-app/versions/8.2.1`

ERROR:
fatal: [local]: FAILED! => {"changed": false, "msg": "parameter error: expecting image to contain [publisher, offer, sku, version] or [name, resource_group]"}

**Comment by rewilliams1** [comment]
Hello, I am receiving this error message when trying to use azure_rm_virtualmachine with Shared Image Gallery.

ERROR:
fatal: [local]: FAILED! => {"changed": false, "msg": "parameter error: expecting image to contain [publisher, offer, sku, version] or [name, resource_group]"}

According to this post i should be able to use the reference id of an image from my shared image gallery. I have verified that the image works by deploying from gallery. Here is the task form my playbook. Can someone tell me what I am doing wrong or what i'm missing?

tasks:
- name: Create FMOS VM
  azure_rm_virtualmachine:
    ad_user: "{{ ad_username }}"
    password: "{{ ad_password }}"
    resource_group: "{{ resource_group }}"
    name: "{{ db_server_name }}"
    vm_size: Standard_E4s_v3
    os_disk_caching: ReadWrite
    admin_username: {{ admin_username }}
    admin_password: "{{ admin_password }}"
    subnet_name: "{{ subnet_name }}"
    virtual_network_name: "{{ vnet_name }}"
    network_interface_names: "{{ db_network_interface }}"
    public_ip_allocation_method: Dynamic
    managed_disk_type: Standard_LRS
    image:
      id: /subscriptions/{{ subscription_id }}/resourceGroups/{{ resource_group }}/providers/Microsoft.Compute/galleries/{{ gallery_name }}/images/rhel-7-app/versions/8.2.1

**Comment by Fred-sun** [comment]
@rewilliams1 I use azure_rm_virtualmachine with Shared Image Gallery in ansible 2.9.0, Create success. 
What is your version of ansible? How is Gallery image created? Ttest log is as follows, Please try agian. Thank you very much!
```e.g.

ok: [127.0.0.1] => {
    "ansible_facts": {
        "azure_vm": {
            "id": "/subscriptions/xxxxxx/resourceGroups/v-xisuRG/providers/Microsoft.Compute/virtualMachines/fredmyVM01",
            "location": "eastus",
            "name": "fredmyVM01",
            "powerstate": "running",
            "properties": {
                "diagnosticsProfile": {
                    "bootDiagnostics": {
                        "enabled": false,
                        "storageUri": null
                    }
                },
                "hardwareProfile": {
                    "vmSize": "Standard_D2s_v3"
                },
                "instanceView": {
                    "computerName": "fredmyVM01",
                    "disks": [
                        {
                            "name": "fredmyVM01",
                            "statuses": [
                                {
                                    "code": "ProvisioningState/succeeded",
                                    "displayStatus": "Provisioning succeeded",
                                    "level": "Info",
                                    "time": "2019-11-01T02:53:34.778763Z"
                                }
                            ]
                        }
                    ],
                    "osName": "ubuntu",
                    "osVersion": "16.04",
                    "statuses": [
                        {
                            "code": "ProvisioningState/succeeded",
                            "displayStatus": "Provisioning succeeded",
                            "level": "Info",
                            "time": "2019-11-01T02:54:39.450986Z"
                        },
                        {
                            "code": "PowerState/running",
                            "displayStatus": "VM running",
                            "level": "Info"
                        }
                    ],
                    "vmAgent": {
                        "extensionHandlers": [],
                        "statuses": [
                            {
                                "code": "ProvisioningState/succeeded",
                                "displayStatus": "Ready",
                                "level": "Info",
                                "message": "Guest Agent is running",
                                "time": "2019-11-01T02:58:15.000Z"
                            }
                        ],
                        "vmAgentVersion": "2.2.44"
                    }
                },
                "networkProfile": {
                    "networkInterfaces": [
                        {
                            "id": "/subscriptions/xxxxxx/resourceGroups/v-xisuRG/providers/Microsoft.Network/networkInterfaces/frednic",
                            "name": "frednic",
                            "properties": {
                                "dnsSettings": {
                                    "appliedDnsServers": [],
                                    "dnsServers": [],
                                    "internalDomainNameSuffix": "z2w1dq2hsh1uvpp5ksd4gayfod.bx.internal.cloudapp.net"
                                },
                                "enableAcceleratedNetworking": false,
                                "enableIPForwarding": false,
                                "hostedWorkloads": [],
                                "ipConfigurations": [
                                    {
                                        "etag": "W/\"7b2daacc-818f-448f-ba3e-a9ba3775f484\"",
                                        "id": "/subscriptions/xxxxxx/resourceGroups/v-xisuRG/providers/Microsoft.Network/networkInterfaces/frednic/ipConfigurations/default",
                                        "name": "default",
                                        "properties": {
                                            "primary": true,
                                            "privateIPAddress": "10.0.1.4",
                                            "privateIPAddressVersion": "IPv4",
                                            "privateIPAllocationMethod": "Dynamic",
                                            "provisioningState": "Succeeded",
                                            "subnet": {
                                                "id": "/subscriptions/xxxxxx/resourceGroups/v-xisuRG/providers/Microsoft.Network/virtualNetworks/fredvnet/subnets/fredsub"
                                            }
                                        }
                                    }
                                ],
                                "macAddress": "00-0D-3A-8A-76-40",
                                "networkSecurityGroup": {
                                    "id": "/subscriptions/xxxxxx/resourceGroups/v-xisuRG/providers/Microsoft.Network/networkSecurityGroups/frednic"
                                },
                                "primary": true,
                                "provisioningState": "Succeeded",
                                "resourceGuid": "5772b937-4ac4-4bdd-bdf2-95c600b37c6d",
                                "tapConfigurations": [],
                                "virtualMachine": {
                                    "id": "/subscriptions/xxxxxx/resourceGroups/v-xisuRG/providers/Microsoft.Compute/virtualMachines/fredmyVM01"
                                }
                            }
                        }
                    ]
                },
                "osProfile": {
                    "adminUsername": "azureuser",
                    "allowExtensionOperations": true,
                    "computerName": "fredmyVM01",
                    "linuxConfiguration": {
                        "disablePasswordAuthentication": false,
                        "provisionVMAgent": true
                    },
                    "secrets": []
                },
                "provisioningState": "Succeeded",
                "storageProfile": {
                    "dataDisks": [],
                    "imageReference": {
                        "id": "/subscriptions/xxxxxx/resourceGroups/v-xisuRG/providers/Microsoft.Compute/galleries/gallery_image/images/image_name/versions/0.0.1"
                    },
                    "osDisk": {
                        "caching": "ReadWrite",
                        "createOption": "FromImage",
                        "diskSizeGB": 30,
                        "managedDisk": {
                            "id": "/subscriptions/xxxxxx/resourceGroups/v-xisuRG/providers/Microsoft.Compute/disks/fredmyVM01",
                            "storageAccountType": "Standard_LRS"
                        },
                        "name": "fredmyVM01",
                        "osType": "Linux"
                    }
                },
                "vmId": "de853c00-5a6c-44ee-8a2b-1e0a1799ee24"
            },
            "tags": {},
            "type": "Microsoft.Compute/virtualMachines",
            "zones": null
        }
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "accept_terms": false,
            "ad_user": null,
            "adfs_authority_url": null,
            "admin_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "admin_username": "azureuser",
            "allocated": true,
            "api_profile": "latest",
            "append_tags": true,
            "auth_source": null,
            "availability_set": null,
            "boot_diagnostics": null,
            "cert_validation_mode": null,
            "client_id": null,
            "cloud_environment": "AzureCloud",
            "custom_data": null,
            "data_disks": null,
            "generalized": false,
            "image": {
                "id": "/subscriptions/xxxxxx/resourceGroups/v-xisuRG/providers/Microsoft.Compute/galleries/gallery_image/images/image_name/versions/0.0.1"
            },
            "license_type": null,
            "location": null,
            "managed_disk_type": "Standard_LRS",
            "name": "fredmyVM01",
            "network_interface_names": [
                "frednic"
            ],
            "open_ports": null,
            "os_disk_caching": "ReadWrite",
            "os_disk_name": null,
            "os_disk_size_gb": null,
            "os_type": "Linux",
            "password": null,
            "plan": null,
            "profile": null,
            "public_ip_allocation_method": "Dynamic",
            "remove_on_absent": [
                "all"
            ],
            "resource_group": "v-xisuRG",
            "restarted": false,
            "secret": null,
            "short_hostname": null,
            "ssh_password_enabled": true,
            "ssh_public_keys": null,
            "started": true,
            "state": "present",
            "storage_account_name": null,
            "storage_blob_name": null,
            "storage_container_name": "vhds",
            "subnet_name": "fredsub",
            "subscription_id": null,
            "tags": null,
            "tenant": null,
            "virtual_network_name": "fredvnet",
            "virtual_network_resource_group": null,
            "vm_identity": null,
            "vm_size": "Standard_D2s_v3",
            "winrm": null,
            "zones": null
        }
    },
    "powerstate_change": null
}

**Comment by rwaal** [comment]
@rewilliams1 Have you installed the Azure modules with the command below?

`ansible-galaxy install azure.azure_modules`

If so, you have a version of the modules without support for the Shared Image Gallery. We use Ansible 2.8.5 and have installed the modules straight from the [azure_modules Github repository](https://github.com/Azure/azure_modules). I'm not sure if Ansible 2.9.0 has the support baked in.

**Comment by rewilliams1** [comment]
> @rewilliams1 I use azure_rm_virtualmachine with Shared Image Gallery in ansible 2.9.0, Create success.
> What is your version of ansible? How is Gallery image created? Ttest log is as follows, Please try agian. Thank you very much!
> 
> ```
> 
> ok: [127.0.0.1] => {
>     "ansible_facts": {
>         "azure_vm": {
>             "id": "/subscriptions/xxxxxx/resourceGroups/v-xisuRG/providers/Microsoft.Compute/virtualMachines/fredmyVM01",
>             "location": "eastus",
>             "name": "fredmyVM01",
>             "powerstate": "running",
>             "properties": {
>                 "diagnosticsProfile": {
>                     "bootDiagnostics": {
>                         "enabled": false,
>                         "storageUri": null
>                     }
>                 },
>                 "hardwareProfile": {
>                     "vmSize": "Standard_D2s_v3"
>                 },
>                 "instanceView": {
>                     "computerName": "fredmyVM01",
>                     "disks": [
>                         {
>                             "name": "fredmyVM01",
>                             "statuses": [
>                                 {
>                                     "code": "ProvisioningState/succeeded",
>                                     "displayStatus": "Provisioning succeeded",
>                                     "level": "Info",
>                                     "time": "2019-11-01T02:53:34.778763Z"
>                                 }
>                             ]
>                         }
>                     ],
>                     "osName": "ubuntu",
>                     "osVersion": "16.04",
>                     "statuses": [
>                         {
>                             "code": "ProvisioningState/succeeded",
>                             "displayStatus": "Provisioning succeeded",
>                             "level": "Info",
>                             "time": "2019-11-01T02:54:39.450986Z"
>                         },
>                         {
>                             "code": "PowerState/running",
>                             "displayStatus": "VM running",
>                             "level": "Info"
>                         }
>                     ],
>                     "vmAgent": {
>                         "extensionHandlers": [],
>                         "statuses": [
>                             {
>                                 "code": "ProvisioningState/succeeded",
>                                 "displayStatus": "Ready",
>                                 "level": "Info",
>                                 "message": "Guest Agent is running",
>                                 "time": "2019-11-01T02:58:15.000Z"
>                             }
>                         ],
>                         "vmAgentVersion": "2.2.44"
>                     }
>                 },
>                 "networkProfile": {
>                     "networkInterfaces": [
>                         {
>                             "id": "/subscriptions/xxxxxx/resourceGroups/v-xisuRG/providers/Microsoft.Network/networkInterfaces/frednic",
>                             "name": "frednic",
>                             "properties": {
>                                 "dnsSettings": {
>                                     "appliedDnsServers": [],
>                                     "dnsServers": [],
>                                     "internalDomainNameSuffix": "z2w1dq2hsh1uvpp5ksd4gayfod.bx.internal.cloudapp.net"
>                                 },
>                                 "enableAcceleratedNetworking": false,
>                                 "enableIPForwarding": false,
>                                 "hostedWorkloads": [],
>                                 "ipConfigurations": [
>                                     {
>                                         "etag": "W/\"7b2daacc-818f-448f-ba3e-a9ba3775f484\"",
>                                         "id": "/subscriptions/xxxxxx/resourceGroups/v-xisuRG/providers/Microsoft.Network/networkInterfaces/frednic/ipConfigurations/default",
>                                         "name": "default",
>                                         "properties": {
>                                             "primary": true,
>                                             "privateIPAddress": "10.0.1.4",
>                                             "privateIPAddressVersion": "IPv4",
>                                             "privateIPAllocationMethod": "Dynamic",
>                                             "provisioningState": "Succeeded",
>                                             "subnet": {
>                                                 "id": "/subscriptions/xxxxxx/resourceGroups/v-xisuRG/providers/Microsoft.Network/virtualNetworks/fredvnet/subnets/fredsub"
>                                             }
>                                         }
>                                     }
>                                 ],
>                                 "macAddress": "00-0D-3A-8A-76-40",
>                                 "networkSecurityGroup": {
>                                     "id": "/subscriptions/xxxxxx/resourceGroups/v-xisuRG/providers/Microsoft.Network/networkSecurityGroups/frednic"
>                                 },
>                                 "primary": true,
>                                 "provisioningState": "Succeeded",
>                                 "resourceGuid": "5772b937-4ac4-4bdd-bdf2-95c600b37c6d",
>                                 "tapConfigurations": [],
>                                 "virtualMachine": {
>                                     "id": "/subscriptions/xxxxxx/resourceGroups/v-xisuRG/providers/Microsoft.Compute/virtualMachines/fredmyVM01"
>                                 }
>                             }
>                         }
>                     ]
>                 },
>                 "osProfile": {
>                     "adminUsername": "azureuser",
>                     "allowExtensionOperations": true,
>                     "computerName": "fredmyVM01",
>                     "linuxConfiguration": {
>                         "disablePasswordAuthentication": false,
>                         "provisionVMAgent": true
>                     },
>                     "secrets": []
>                 },
>                 "provisioningState": "Succeeded",
>                 "storageProfile": {
>                     "dataDisks": [],
>                     "imageReference": {
>                         "id": "/subscriptions/xxxxxx/resourceGroups/v-xisuRG/providers/Microsoft.Compute/galleries/gallery_image/images/image_name/versions/0.0.1"
>                     },
>                     "osDisk": {
>                         "caching": "ReadWrite",
>                         "createOption": "FromImage",
>                         "diskSizeGB": 30,
>                         "managedDisk": {
>                             "id": "/subscriptions/xxxxxx/resourceGroups/v-xisuRG/providers/Microsoft.Compute/disks/fredmyVM01",
>                             "storageAccountType": "Standard_LRS"
>                         },
>                         "name": "fredmyVM01",
>                         "osType": "Linux"
>                     }
>                 },
>                 "vmId": "de853c00-5a6c-44ee-8a2b-1e0a1799ee24"
>             },
>             "tags": {},
>             "type": "Microsoft.Compute/virtualMachines",
>             "zones": null
>         }
>     },
>     "changed": false,
>     "invocation": {
>         "module_args": {
>             "accept_terms": false,
>             "ad_user": null,
>             "adfs_authority_url": null,
>             "admin_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
>             "admin_username": "azureuser",
>             "allocated": true,
>             "api_profile": "latest",
>             "append_tags": true,
>             "auth_source": null,
>             "availability_set": null,
>             "boot_diagnostics": null,
>             "cert_validation_mode": null,
>             "client_id": null,
>             "cloud_environment": "AzureCloud",
>             "custom_data": null,
>             "data_disks": null,
>             "generalized": false,
>             "image": {
>                 "id": "/subscriptions/xxxxxx/resourceGroups/v-xisuRG/providers/Microsoft.Compute/galleries/gallery_image/images/image_name/versions/0.0.1"
>             },
>             "license_type": null,
>             "location": null,
>             "managed_disk_type": "Standard_LRS",
>             "name": "fredmyVM01",
>             "network_interface_names": [
>                 "frednic"
>             ],
>             "open_ports": null,
>             "os_disk_caching": "ReadWrite",
>             "os_disk_name": null,
>             "os_disk_size_gb": null,
>             "os_type": "Linux",
>             "password": null,
>             "plan": null,
>             "profile": null,
>             "public_ip_allocation_method": "Dynamic",
>             "remove_on_absent": [
>                 "all"
>             ],
>             "resource_group": "v-xisuRG",
>             "restarted": false,
>             "secret": null,
>             "short_hostname": null,
>             "ssh_password_enabled": true,
>             "ssh_public_keys": null,
>             "started": true,
>             "state": "present",
>             "storage_account_name": null,
>             "storage_blob_name": null,
>             "storage_container_name": "vhds",
>             "subnet_name": "fredsub",
>             "subscription_id": null,
>             "tags": null,
>             "tenant": null,
>             "virtual_network_name": "fredvnet",
>             "virtual_network_resource_group": null,
>             "vm_identity": null,
>             "vm_size": "Standard_D2s_v3",
>             "winrm": null,
>             "zones": null
>         }
>     },
>     "powerstate_change": null
> }
> ```

Hey thanks for the quick reply. I am running ansible 2.8.6 in a virtual environment. The image gallery was created via azure cli commands. Looks like 2.9 was released 10/31 , so will try it out.

**Comment by rewilliams1** [comment]
> @rewilliams1 Have you installed the Azure modules with the command below?
> 
> `ansible-galaxy install azure.azure_modules`
> 
> If so, you have a version of the modules without support for the Shared Image Gallery. We use Ansible 2.8.5 and have installed the modules straight from the [azure_modules Github repository](https://github.com/Azure/azure_modules). I'm not sure if Ansible 2.9.0 has the support baked in.

Thanks for the reply, It looks like 2.9.0 was released yesterday and @Fred-sun said it was baked in. I will try to upgrade to see if that helps , and if not I will do your suggestion.

**Comment by rewilliams1** [comment]
I upgraded to 2.9 and it worked, thanks guys!

**Comment by neerajsingh315** [comment]
For me, The old apiVersion in the Virtual Machine arm template was causing the exception while using a shared image gallery: The value of parameter imageReference.id is invalid
I Fixed the issue by updating the apiVersion. I was using version ‘2017-03-30’ however once I changed to version ‘2019-03-01’ it went through ok without the error.  Thanks.
