### ISSUE TITLE
azure_rm_virtualmachinescaleset > upgrade_policy required

### ISSUE THREAD

**Issue by nergalex** [Azure/azure_preview_modules#259]
Hi,

Regarding azure_rm_virtualmachinescaleset module, examples does not provide "upgrade_policy" parameter while it is required:  `Azure Error: InvalidParameter\nMessage: Required parameter 'upgradePolicy.mode' is missing (null).\nTarget: upgradePolicy.mode`

**Comment by Fred-sun** [comment]
@MyronFanQiu The associated PR has been merged, can you close this Issue? Thank you very much!
