### ISSUE TITLE
Subnet endpoints not being created on first run

### ISSUE THREAD

**Issue by Dagon-** [Azure/azure_preview_modules#262]
I am trying to create an subnet with endpoints. The enpoints are not being created along with the subnet. If the task is run a second time the enpoints are added. I'm using the 2.8 release of the preview modules.

Here is the variable  and task I'm using:

    subnets:
      - name: "{{ env_name }}-sn"
        cidr: 27
        index: 0
        endpoints: []
      - name: "{{ env_name }}-k8s-sn"
        cidr: 24
        index: 1
        endpoints: 
          - service: Microsoft.Sql
          - service: Microsoft.AzureCosmosDB
          - service: Microsoft.EventHub

    - name: Create subnet
      azure_rm_subnet:
        resource_group: "{{ env_rg }}"
        virtual_network_name: "{{ env_name }}-vnet"
        name: "{{ item.name }}-subnet"
        address_prefix_cidr: "{{ vnet_base | ipsubnet(item.cidr, item.index) }}"
        service_endpoints: "{{ item.endpoints }}"
      loop: "{{ subnets }}"
      register: create_subnet
      retries: 2
      delay: 30
      until: create_subnet is succeeded

This is run and the subnet is created.
An `az network vnet subnet show` shows us there are no endpoints:

    {
      "addressPrefix": "<REDACTED>",
      "addressPrefixes": null,
      "delegations": [],
      "etag": "W/\"<REDACTED>"",
      "id": "<REDACTED>",
      "interfaceEndpoints": null,
      "ipConfigurationProfiles": null,
      "ipConfigurations": null,
      "name": "sl-k8s-sn-subnet",
      "networkSecurityGroup": null,
      "provisioningState": "Succeeded",
      "purpose": null,
      "resourceGroup": "<REDACTED>",
      "resourceNavigationLinks": null,
      "routeTable": null,
      "serviceAssociationLinks": null,
      "serviceEndpointPolicies": null,
      "serviceEndpoints": null,
      "type": "Microsoft.Network/virtualNetworks/subnets"
    }

If the above task is run for a second time the subnet is updated and the endpoints added:

    {
      "addressPrefix": "<REDACTED>",
      "addressPrefixes": null,
      "delegations": [],
      "etag": "W/\""<REDACTED>"",
      "id": ""<REDACTED>",
      "interfaceEndpoints": null,
      "ipConfigurationProfiles": null,
      "ipConfigurations": null,
      "name": "sl-k8s-sn-subnet",
      "networkSecurityGroup": null,
      "provisioningState": "Succeeded",
      "purpose": null,
      "resourceGroup": ""<REDACTED>",
      "resourceNavigationLinks": null,
      "routeTable": null,
      "serviceAssociationLinks": null,
      "serviceEndpointPolicies": null,
      "serviceEndpoints": [
        {
          "locations": [
            "northeurope"
          ],
          "provisioningState": "Succeeded",
          "service": "Microsoft.Sql"
        },
        {
          "locations": [
            "*"
          ],
          "provisioningState": "Succeeded",
          "service": "Microsoft.AzureCosmosDB"
        },
        {
          "locations": [
            "*"
          ],
          "provisioningState": "Succeeded",
          "service": "Microsoft.EventHub"
        }
      ],
      "type": "Microsoft.Network/virtualNetworks/subnets"
    }

I have tried adding the locations to the `subnet` variable but it does not appear to make a difference.

**Comment by yuwzho** [comment]
@Dagon- I add a fix to the Ansible upstream, you can install the branch to try the PR without role

```
pip install git+https://github.com/VSChina/ansible.git@yuwzho-subnet
```

**Comment by Dagon-** [comment]
@yuwzho 

That is working as expected now. Thank you!

**Comment by Fred-sun** [comment]
@yuwzho The PR has been merged, Could you can closed this issue? Thank you very much!

**Comment by MyronFanQiu** [comment]
@Fred-sun Thanks. Due to the PR has been merged. close this issue. If anything happened, we can reopen this one.
