### ISSUE TITLE
Support service principal creation

### ISSUE THREAD

**Issue by yuwzho** [Azure/azure_preview_modules#265]
Support creating service principal as Azure CLI: https://docs.microsoft.com/en-us/cli/azure/ad/sp?view=azure-cli-latest#az-ad-sp-create

No need to support the assignment, which should be supported by azure_rm_roledefinition.

Then we can use the azure_rm_serviceprincipal together with azure_rm_roledefinition to create a service principal and assign role to it.

**Comment by Fred-sun** [comment]
@MyronFanQiu Please help take a look this issue when you're free! Thank you very much!

**Comment by Fred-sun** [comment]
@MyronFanQiu Are you working on this problem? Could you please help to update the processing progress of this problem? Thanks a lot!

**Comment by Fred-sun** [comment]
@MyronFanQiu Do you have any update for this! Please. Thanks a lot!

**Comment by Fred-sun** [comment]
@MyronFanQiu Will you create this module(azure_rm_serviceprincipal)?

**Comment by Fred-sun** [comment]
@MyronFanQiu

**Comment by Fred-sun** [comment]
@mybayern1974 Please take a look at this issue when you're free! Thanks a lot!

**Comment by Fred-sun** [comment]
@haiyuazhang Would you please help take a look this issue？

**Comment by Fred-sun** [comment]
@gavinfish @haiyuazhang

**Comment by Fred-sun** [comment]
@yuwzho Thank you very much for your interest in Ansible. This repo is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/azure
Please re-submit this Issue in the above repository and closed this. Thank you very much!
