### ISSUE TITLE
Storage account deletion failed in VM test

### ISSUE THREAD

**Issue by yuwzho** [Azure/azure_preview_modules#266]
https://travis-ci.org/Azure/azure_preview_modules/jobs/534634265

Which also shows in the upstream. The VM's `_own_sa_` tag is set to an non existing storage account and failed when deletion from this change: https://github.com/ansible/ansible/commit/75788ecff4520182c1e14a4414f377fdf4820f0b

**Comment by Fred-sun** [comment]
@yuwzho The PR [#57102 ](https://github.com/ansible/ansible/pull/57102)has fixed the bug, Could we can closed this issue? Thanks a lot!

**Comment by Fred-sun** [comment]
@yuwzho Could we can closed this issue? Please take a look when you're free! Thanks a lot!
