### ISSUE TITLE
azure_rm_loadbalancer health probe does not support HTTPS protocol

### ISSUE THREAD

**Issue by andyeff** [Azure/azure_preview_modules#277]
Hello,

I'm creating load balancers using the azure_rm_loadbalancer module but have noticed one key issue - health probes cannot be defined as HTTPS. Attempting to do so will cause the playbook to throw an error during invocation.

This setting *can* be configured in the Portal, and I imagine creating a health probe initially as HTTP and then running an API call to switch it to HTTPS is a potential workaround, but this causes idempotency issues if re-running a load balancer playbook against ones that are modified in this way, as I suspect Ansible will attempt to reconfigure the HTTPS health probe back to HTTP.

**Comment by MyronFanQiu** [comment]
@andyeff  Hello. Thanks for opening this issue! I will track this one and share any update with you.

**Comment by MyronFanQiu** [comment]
@andyeff Hello. I checked the code. When this module originally created, the health probe doesn't support HTTPS protocol. Last year, around Nov, the API version of the dependent SDK was updated and now it indeed support the HTTPS protocol. I will add this feature and test it as soon. Thanks for this issue!

**Comment by yungezz** [comment]
hi @MyronFanQiu  pls help to make sure the upstream fix  was synced to role repo also.

**Comment by MyronFanQiu** [comment]
@andyeff Hi. The new feature has been merged. Tomorrow there will be a sync PR between this role repo and the main ansible repo. I will merge that one as soon.

**Comment by Fred-sun** [comment]
@andyeff @MyronFanQiu The related PR has been merged. Is it possible to close this Issue? Please confirm, Thank you very much!
