### ISSUE TITLE
Application gateway with SSL

### ISSUE THREAD

**Issue by Tomelin** [Azure/azure_preview_modules#288]
Hi dear,

I use azure_rm with module 'azure_rm_appgateway' for configuration the Azure Application Gateway, but how insert certificate SSL in ''authentication_certificates / data '?

I have a file certificate.cer or certificate.pfx, but I don`t know import certificate in this module.

**Comment by Fred-sun** [comment]
@Tomelin Thanks for your open this issue. I will check how to insert certificate SSL. Thanks a lot!

**Comment by Fred-sun** [comment]
@Tomelin Perhaps you can introduce your credentials this way, Please try! Thank you very much!
```e.g.
    ssl_certificates:
      - name: cert2
        password: your-password
        data: "{{ lookup('file', 'certificate.pfx') }}"

**Comment by Fred-sun** [comment]
@Tomelin Are these helpful to you?

**Comment by Fred-sun** [comment]
kindly ping

**Comment by Tomelin** [comment]
Sorry for delay, but my tests is not work:

This return error:

An unhandled exception occurred while running the lookup plugin 'file'. Error was a <type 'exceptions.UnicodeDecodeError'>, original message: 'utf8' codec can't decode byte 0x82 in position 1: invalid start byte

The module not know certificate, because is not encode.

**Comment by Fred-sun** [comment]
@Tomelin Should be your certificate file format problem, you can use this try ( [file link](https://github.com/Azure/azure_preview_modules/tree/master/tests/integration/targets/azure_rm_appgateway/files))! Thank you very much!

**Comment by Tomelin** [comment]
Thanks,

But how to generate the certificate this format?  

Have you example?

**Comment by Fred-sun** [comment]
@tomelin You might want to try this[ link](https://www.rosehosting.com/blog/how-to-generate-a-self-signed-ssl-certificate-on-linux/)! Thanks a lot!

**Comment by Fred-sun** [comment]
@Tomelin Can this link help you? Thank you very much!
