### ISSUE TITLE
azure_rm_keyvaultsecret doesn't update existing secrets

### ISSUE THREAD

**Issue by bbgobie** [Azure/azure_preview_modules#301]
This module doesn't seem to update the values if a secret exists.  I would expect a new version to be created and shown in the key vault but none shows up and the existing secret never changes.

The SP I'm using to create/update the secret has everything selected for secrets in access policies although I would hope get/list/set/delete would be enough.  The SP is also a contributor in Access Control

Sample code to duplicate
----------------------------------------
```
- name: Create a secret
  azure_rm_keyvaultsecret:
    secret_name: MySecret
    secret_value: "Secret Value 1"
    keyvault_uri: <YOUR_URI>
    state: present
    
- name: Update a secret
  azure_rm_keyvaultsecret:
    secret_name: MySecret
    secret_value: "Secret Value 2"
    keyvault_uri: <YOUR_URI>
    state: present
```

pip freeze
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
adal==1.2.1
ansible==2.7.7
applicationinsights==0.11.9
argcomplete==1.10.0
asn1crypto==0.24.0
attrs==19.1.0
awscli==1.16.38
azure==4.0.0
azure-applicationinsights==0.1.0
azure-batch==4.1.3
azure-cli-core==2.0.35
azure-cli-nspkg==3.0.2
azure-common==1.1.11
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.5
azure-datalake-store==0.0.46
azure-eventgrid==1.3.0
azure-graphrbac==0.40.0
azure-keyvault==1.0.0a1
azure-loganalytics==0.1.0
azure-mgmt==4.0.0
azure-mgmt-advisor==1.0.1
azure-mgmt-applicationinsights==0.1.1
azure-mgmt-authorization==0.51.1
azure-mgmt-batch==5.0.1
azure-mgmt-batchai==2.0.0
azure-mgmt-billing==0.2.0
azure-mgmt-cdn==3.0.0
azure-mgmt-cognitiveservices==3.0.0
azure-mgmt-commerce==1.0.1
azure-mgmt-compute==4.4.0
azure-mgmt-consumption==2.0.0
azure-mgmt-containerinstance==1.4.0
azure-mgmt-containerregistry==2.0.0
azure-mgmt-containerservice==4.4.0
azure-mgmt-cosmosdb==0.5.2
azure-mgmt-datafactory==0.6.0
azure-mgmt-datalake-analytics==0.6.0
azure-mgmt-datalake-nspkg==3.0.1
azure-mgmt-datalake-store==0.5.0
azure-mgmt-datamigration==1.0.0
azure-mgmt-devspaces==0.1.0
azure-mgmt-devtestlabs==3.0.0
azure-mgmt-dns==2.1.0
azure-mgmt-eventgrid==1.0.0
azure-mgmt-eventhub==2.6.0
azure-mgmt-hanaonazure==0.1.1
azure-mgmt-hdinsight==0.1.0
azure-mgmt-iotcentral==0.1.0
azure-mgmt-iothub==0.7.0
azure-mgmt-iothubprovisioningservices==0.2.0
azure-mgmt-keyvault==1.1.0
azure-mgmt-loganalytics==0.2.0
azure-mgmt-logic==3.0.0
azure-mgmt-machinelearningcompute==0.4.1
azure-mgmt-managementgroups==0.1.0
azure-mgmt-managementpartner==0.1.1
azure-mgmt-maps==0.1.0
azure-mgmt-marketplaceordering==0.1.0
azure-mgmt-media==1.0.0
azure-mgmt-monitor==0.5.2
azure-mgmt-msi==0.2.0
azure-mgmt-network==2.3.0
azure-mgmt-notificationhubs==2.1.0
azure-mgmt-nspkg==2.0.0
azure-mgmt-policyinsights==0.1.0
azure-mgmt-powerbiembedded==2.0.0
azure-mgmt-rdbms==1.4.1
azure-mgmt-recoveryservices==0.3.0
azure-mgmt-recoveryservicesbackup==0.3.0
azure-mgmt-redis==5.0.0
azure-mgmt-relay==0.1.0
azure-mgmt-reservations==0.2.1
azure-mgmt-resource==2.1.0
azure-mgmt-scheduler==2.0.0
azure-mgmt-search==2.1.0
azure-mgmt-servicebus==0.5.3
azure-mgmt-servicefabric==0.2.0
azure-mgmt-signalr==0.1.1
azure-mgmt-sql==0.10.0
azure-mgmt-storage==3.1.0
azure-mgmt-subscription==0.2.0
azure-mgmt-trafficmanager==0.50.0
azure-mgmt-web==0.41.0
azure-nspkg==2.0.0
azure-servicebus==0.21.1
azure-servicefabric==6.3.0.0
azure-servicemanagement-legacy==0.20.6
azure-storage==0.35.1
azure-storage-blob==1.5.0
azure-storage-common==1.4.2
azure-storage-file==1.4.0
azure-storage-nspkg==3.1.0
azure-storage-queue==1.4.0
backports.ssl-match-hostname==3.7.0.1
bcrypt==3.1.6
boto==2.49.0
boto3==1.9.28
botocore==1.12.28
cachetools==3.1.0
certifi==2019.3.9
cffi==1.12.3
chardet==3.0.4
colorama==0.3.9
configparser==3.7.4
cryptography==2.6.1
dictdiffer==0.8.0
docutils==0.14
entrypoints==0.3
enum34==1.1.6
futures==3.2.0
google-auth==1.6.3
humanfriendly==4.18
idna==2.8
ipaddress==1.0.22
isodate==0.6.0
Jinja2==2.10.1
jmespath==0.9.4
keyring==18.0.1
knack==0.3.3
kubernetes==7.0.0
MarkupSafe==1.1.1
monotonic==1.5
msrest==0.6.1
msrestazure==0.5.0
ntlm-auth==1.3.0
oauthlib==3.0.1
openshift==0.7.2
packaging==19.1
paramiko==2.4.2
pathlib2==2.3.4
pyasn1==0.4.5
pyasn1-modules==0.2.5
pycparser==2.19
Pygments==2.4.2
PyJWT==1.7.1
PyNaCl==1.3.0
pyOpenSSL==19.0.0
pyparsing==2.4.2
python-dateutil==2.8.0
python-string-utils==0.6.0
pywinrm==0.3.0
PyYAML==3.13
requests==2.21.0
requests-credssp==1.0.2
requests-ntlm==1.1.0
requests-oauthlib==1.2.0
rsa==3.4.2
ruamel.ordereddict==0.4.13
ruamel.yaml==0.15.94
s3transfer==0.1.13
scandir==1.10.0
SecretStorage==2.3.1
six==1.12.0
tabulate==0.8.2
typing==3.7.4
urllib3==1.23
websocket-client==0.56.0
xmltodict==0.12.0

**Comment by Fred-sun** [comment]
@bbgobie Thank you for opening this issue, We'll look into that. Thank you very much!

**Comment by Fred-sun** [comment]
@MyronFanQiu Could you help take a look this issue? It seem duplicate with [#52082](https://github.com/ansible/ansible/issues/52082). Thank you very much!

**Comment by Fred-sun** [comment]
@MyronFanQiu This Issue has been repaired by PR [#303](https://github.com/Azure/azure_preview_modules/pull/303), maybe we can close it! Thank you very much!
