### ISSUE TITLE
documentation - wrong module name in example

### ISSUE THREAD

**Issue by nergalex** [Azure/azure_preview_modules#310]
##### ISSUE TYPE
 - Documentation Report

##### MODULE
azure_rm_virtualmachinescalesetinstance_facts

##### SUMMARY
Wrong module name "azure_rm_computevirtualmachinescalesetinstance_facts" at
https://github.com/Azure/azure_preview_modules/blob/master/library/azure_rm_virtualmachinescalesetinstance_facts.py#L50

**Comment by Fred-sun** [comment]
@nergalex It has been fixed, can be closed! Thanks a lot!

**Comment by Fred-sun** [comment]
close_me
