### ISSUE TITLE
azure_keyvault_secret: Error when using with example syntax

### ISSUE THREAD

**Issue by jpdias92** [Azure/azure_preview_modules#336]
I'm trying to use the `azure_keyvault_secret` lookup plugin and have tried all kinds of syntax variations, starting from the example in the source code of course. I always get the following error:

```
fatal: [localhost]: FAILED! => {"msg": "the field 'args' has an invalid value ({'msg': \"the value of this secret is {{lookup('azure_keyvault_secret',secretname,vault_url=url, client_id=client_id, secret=secret, tenant_id=tenant)}}\"}), and could not be converted to an dict.The error was: Expecting value: line 1 column 1 (char 0)\n\nThe error appears to be in '_azure_keyvault_secret_lookup.yml': line 8, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Look up secret when ansible host is general VM\n      ^ here\n"}
```

**Steps to reproduce:**
I'm testing with the following playbook, that uses an exact copy of the [example for general VMs](https://github.com/Azure/azure_preview_modules/blob/9b5477e07a70b6c5768dfe8e1ad52981fa2458cf/lookup_plugins/azure_keyvault_secret.py#L42) from the source code (including the typo `cliend_id=` but when I fix that I get exactly the same error too):
```
- hosts: localhost
  roles: 
    - azure.azure_preview_modules
  vars:
    skip_azure_sdk: false  # Prevent azure_preview_modules of trying to update Python SDK
  tasks:

    - name: Look up secret when ansible host is general VM
      vars:
        url: 'https://yourvault.vault.azure.net'
        secretname: 'testSecret/version'
        client_id: '123456789'
        secret: 'abcdefg'
        tenant: 'uvwxyz'
      debug: msg="the value of this secret is {{lookup('azure_keyvault_secret',secretname,vault_url=url, cliend_id=client_id, secret=secret, tenant_id=tenant)}}"
```

**Ansible version:**
```
ansible 2.8.6
  config file = /home/xjood/.ansible.cfg
  configured module search path = ['/home/xjood/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
```

The md5 checksum of my local file `azure_keyvault_secret.py` matches the one taken from the master branch of the repo:
`13ad014a0c43b2fd8560d3ac0d4ed7e0`

Of course in my playbook I'm using the dummy values provided in the example but I've tried to replace them with the correct values multiple times and got the same error. I would expect to receive some error saying the vault does not exist or the tenant does not exist or something similar.

**Comment by rdonkin** [comment]
I also found that the example code is wrong.  Here is some code that does work  at least with Ansible 2.9.2 and latest version of the lookup plugin

```
    - set_fact:
        keyvault_name: "my-amazing-keyvault"

    - set_fact:
        keyvault_uri: "https://{{ keyvault_name }}.vault.azure.net/"

    - name: Look up secret when Ansible host is non-MSI VM
      debug:
        msg: "secret value = {{ lookup('azure_keyvault_secret', secretname, vault_url=url, client_id=client_id, secret=secret, tenant_id=tenant) }}"
      vars:
        url: "{{ keyvault_uri }}"
        secretname: 'ExamplePassword'         # No /version suffix, unlike example in code
        client_id: "{{ principal_id }}"       # Service principal object ID (application ID / client ID)
        secret: "{{ azure_secret }}"          # Service principal secret
        tenant: "{{ tenant_id }}"

    # For performance comparison
    - name: Get secret with Azure CLI
      shell: |
        set -x
        az keyvault secret show --vault-name {{ keyvault_name }} --name "ExamplePassword"
```

### Performance

However, it takes over 2 minutes to look up a secret, whereas Azure CLI takes 3 seconds.  This is repeatable and both are using service principal (SP) mode.

The `azure_rm_keyvaultsecret` module also takes about 2 minutes to create  secret in SP mode. This takes about 3 seconds in Azure CLI.

Unless there's a dramatic speedup, this lookup plugin and the `azure_rm_keyvaultsecret` module are not usable for me.

**Comment by Fred-sun** [comment]
@haiyuazhang @gavinfish Would you please help take a look this issue? Thank you very much!

**Comment by haiyuazhang** [comment]
@rdonkin 
I test the plugin using the latest ansible version. For serval runs, Although it was slower than az cli but
it only takes around 10 secs to finish.

Did you set "skip_azure_sdk: false" ? If not, the preview module will try to update python sdk first and the updating itself might take minutes to finish.

**Comment by rdonkin** [comment]
@haiyuazhang  I did use `skip_azure_sdk: false` when importing the module, earlier in the playbook: 

```
- include_role:
    name: azure.preview-modules
  vars:
    skip_azure_sdk: false
```

 I don't see how this setting could affect the invocation of a lookup plugin in a separate task, and in any case that `pip install -r` should complete quickly when the dependencies are already installed - so I don't think this is the source of the slowdown.

On the secret creation which  takes about 2 minutes with this module, compared to a few seconds for Azure CLI, here's the code I used:
```
- block:
    - azure_rm_keyvaultsecret:
        keyvault_uri: "{{ keyvault_uri }}"
        secret_name: testsecret
        secret_value: 'mysecret'
      no_log: "{{ no_logging }}"
```

**Comment by jpdias92** [comment]
Meanwhile, I continue to have the original problem, even following @rdonkin example. Here goes the test snippet I'm using. I've replaced again all values with a `"test"` string but the result when using the actual values was exactly the same:

```
    - name: Lookup secret when Ansible host is non-MSI VM
      debug:
        msg: "secret value = {{ lookup('azure_keyvault_secret', secretname, vault_url=url, client_id=client_id, secret=secret, tenant_id=tenant) }}"
      vars:
        url: "test"
        secretname: "test"
        client_id: "test"
        secret: "test"
        tenant: "test"
```

I start to suspect this may be related to my Python environment... I have just reinstalled `azure.azure_preview_modules (2.9.1)` role. I've also installed the requirements.

**Ansible version:**
```
ansible 2.9.2
  config file = /home/xjood/.ansible.cfg
  configured module search path = ['/home/xjood/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]
```

For the python environment, here is the result of `pip freeze`: [pip_freeze.txt](https://github.com/Azure/azure_preview_modules/files/4025945/pip_freeze.txt)

**Comment by rdonkin** [comment]
@jpdias92 Your error appears to be from Ansible, not the lookup plugin - yet you are using same code as me, and same Ansible version.  It may be due to the data returned by lookup plugin though.

Things to try:

- break the debug command into a set_fact, then use that var with `debug: var=myvar`.
- run with `-vvvvv` and paste output for these tasks - I believe this shows if lookup plugin is being invoked

**Comment by jpdias92** [comment]
@rdonkin thanks for the new ideas! Unfortunately, still the same behavior...  

I'm now working on running Ansible inside Docker containers. If it's something about my environment, maybe I'll get more insights once I experiment running this in a more controlled environment.

I'll update this issue with any new findings.

**Comment by taaarpa6** [comment]
Hi @jpdias92 ,

I have encountered the same issue, when using the lookup functionality for Azure Key Vault Secrets.
The script does work but I have seen the case, where the API call returned a 404 and not a network exception. This 404 is not checked and leads to an error when the access_token is extracted from the request response, see https://github.com/Azure/azure_preview_modules/blob/master/lookup_plugins/azure_keyvault_secret.py#L103.
From ansible point of view, (I assume) this will return "the field 'args' has an invalid value".

The solution is simple. Before accessing the response of the request, a condition should check the response code:
```
try:
    token_res = requests.get('http://169.254.169.254/metadata/identity/oauth2/token', params=token_params, headers=token_headers)
    if token_res.ok:
        token = token_res.json().get("access_token")
```

The block (https://github.com/Azure/azure_preview_modules/blob/master/lookup_plugins/azure_keyvault_secret.py#L101L110) should be replaced with

```
try:
    token_res = requests.get('http://169.254.169.254/metadata/identity/oauth2/token', params=token_params, headers=token_headers)
    if token_res.ok:
        token = token_res.json().get("access_token")
        if token is not None:
            TOKEN_ACQUIRED = True
        else:
            display.v('Successfully called MSI endpoint, but no token was available. Will use service principal if provided.')
except requests.exceptions.RequestException:
    display.v('Unable to fetch MSI token. Will use service principal if provided.')
    TOKEN_ACQUIRED = False
```

May I ask you to test the modified section and update the python script? - Thanks in advance!

**Comment by jpdias92** [comment]
@taaarpa6, it works perfectly! 😄But with your fix, now I'm able to successfully retrieve the secret, I'm not receiving any 404. Although I'm getting a message saying `Your credentials class does not support session injection. Performance will not be at the maximum.`, maybe that was the reason it was failing without your fix? Anyway, you should definitely try to submit a Pull Request to fix this!

@rdonkin and @haiyuazhang , regarding the performance, it is taking between 1 and 3 seconds to retrieve the secret so no performance problem on my side.

**Comment by taaarpa6** [comment]
@jpdias92 
The 404 I could reproduce when executing the python commands manually, otherwise, you do not see it. The message, «Your credentials class does not support session injection. Performance will not be at the maximum», is shown for me as well.

Pull request is created, let hope it gets approved soon.

**Comment by Fred-sun** [comment]
@ jpdias92Can you try the above PR to see if it meets your needs? Thank you very much!

**Comment by jpdias92** [comment]
> @ jpdias92Can you try the above PR to see if it meets your needs? Thank you very much!

Done! Left a comment in the PR: https://github.com/Azure/azure_preview_modules/pull/349#issuecomment-582968487

**Comment by Fred-sun** [comment]
@jpdias92 Thank you very much for your interest in Ansible. This repo is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/azure
Please re-submit this Issue in the above repository and closed this. Thank you very much!

**Comment by jpdias92** [comment]
I'm not sure if the issue will still be relevant in the other repo, as this lookup plugin does not seem to have been moved, and now we can use a module seems to do the job of retrieving secrets: https://github.com/ansible-collections/azure/blob/dev/plugins/modules/azure_rm_keyvaultsecret_info.py


I'll simply mark it as closed then.

**Comment by rdonkin** [comment]
Are there plans to port the lookup plugin?  This is far more convenient than using a module, as the plugin lets you write a single line of code to get a parameter, rather than a task registering a var then using that var in second task.

AWS Parameter Store (another secrets manager service) has a similar lookup plugin.
