### ISSUE TITLE
azure_rm_keyvault module not update access_policies for a keyvault

### ISSUE THREAD

**Issue by Eugen1987** [Azure/azure_preview_modules#370]
Hi.

When we try to update access policies the module not update it:

- name: "Update keyvault"
      azure_rm_keyvault:
        resource_group: "{{ rg }}"
        vault_name: "{{ kv }}"
        enabled_for_deployment: true
        vault_tenant: "{{ vt}}"
        enable_soft_delete: "false"
        sku:
          name: standard
        access_policies:
          - tenant_id: "{{ t }}"
            object_id: "{{ oid }}"
            keys:
              - encrypt
              - decrypt
            certificates:
              - get
              - list
            secrets:
              - get
              - list

when we change  the  access_policies like this :

        access_policies:
          - tenant_id: "{{ t }}"
            object_id: "{{ oid }}"
            keys:
              - encrypt
            certificates:
              - get
            secrets:
              - get

the module not update it.

**Comment by Fred-sun** [comment]
@Eugen1987 Thank you for taking the time to report this question. We will ansible 's azure module related Issue and PR is transferred to azure collection (https://github.com/ansible-collections/azure/issues), you can transfer the Issue to azure collection repo?

**Comment by Eugen1987** [comment]
oks, i will transfer it

**Comment by Eugen1987** [comment]
transfered to collection-azure : azure_rm_keyvault module does not update access_policies for a keyvault #56
