### ISSUE TITLE
azure_rm_storageblob Add parameter static-website

### ISSUE THREAD

**Issue by avi-beetul** [Azure/azure_preview_modules#374]
Hi All

Excuse my ignorance, I can't find out how to enable static websites on the blob service in the Ansible module. 
I wonder if I'm missing that functionality on a different module and whether there's a short term workaround?

**Comment by Fred-sun** [comment]
@avi-beetul Thank you for taking the time to report this problem. We will investigate and solve this problem as soon as possible. Thank you very much!

**Comment by Fred-sun** [comment]
@haiyuazhang Would you help to add the parameter for azure_rm_storageblob module? Thank you very much!

**Comment by Fred-sun** [comment]
@haiyuazhang Would you help to add the parameter for azure_rm_storageblob module? Thank you very much!

**Comment by Fred-sun** [comment]
@avi-beetul Thank you very much for your interest in Ansible. This repo is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/azure
Please re-submit this Issue in the above repository and closed this. Thank you very much!
