### ISSUE TITLE
Dead repository?

### ISSUE THREAD

**Issue by TheTechOddBug** [Azure/azure_preview_modules#398]
Is this repository still alive? A long time ago without commits. Any other place for this? Should we switch to community instead of this one? How are this and community related? Thank you very much in advance.

**Comment by mybayern1974** [comment]
Hi @TheTechOddBug , for Ansible Azure related questions/contributions, it's suggested to move to [here](https://github.com/ansible-collections/azure). With that I'm closing this issue.
