### ISSUE TITLE
Microsoft.RecoveryServices/vaults/backupPolicies: Provided parameter value not valid - ScheduleRunTimes 

### ISSUE THREAD

**Issue by ajaguilar-viewnext** [Azure/azure_preview_modules#97]
Error message: 'The provided value for the template parameter 'scheduleRunTimes' at line '1' and column '1408' is not valid.'.

When: Using azure_rm_deployment module 

Parameter and value provided: extract from multiple examples [Protection policies API](https://docs.microsoft.com/en-us/rest/api/backup/protectionpolicies/createorupdate#create_or_update_simple_azure_vm_protection_policy)
Parameters:
"scheduleRunTimes": {
      "type": "array",
      "metadata": {
        "description": "Times in day when backup should be triggered. e.g. 01:00, 13:00 [2018-06-01T01:00:00Z]. This will be used in LTR too for daily, weekly, monthly and yearly backup."
      }
Resources:
"scheduleRunTimes": [
      **"2018-06-07T01:00:00Z"**
 ]

Any help is pretty much apprecited.

Thanks in advance.

**Comment by ajaguilar-viewnext** [comment]
@Fred-sun Of course. That format was the first I tried. 
Digging in [Azure API documentation](https://docs.microsoft.com/en-us/rest/api/backup/protectionpolicies/createorupdate#create_or_update_simple_azure_vm_protection_policy) I found out examples using the format I pointed in the issue. 

What is the right format? I have errors using both maybe the error could be in other part of my json template... here I attatch

```javascript
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "vaultName": {
      "type": "string",
      "metadata": {
        "description": "Name of the Recovery Services Vault"
      }
    },
    "policyName": {
      "type": "string",
      "metadata": {
        "description": "Name of the Backup Policy"
      }
    },
    "scheduleRunFrequency": {
      "type": "string",
      "metadata": {
        "description": "Daily, Weekly"
      }   
    },
    "scheduleRunTimes": {
      "type": "array",
      "metadata": {
        "description": "Times in day when backup should be triggered. e.g. 01:00, 13:00 [2018-06-01T01:00:00Z]. This will be used in LTR too for daily, weekly, monthly and yearly backup."
      }
    },
    "timeZone": {
      "type": "string",
      "metadata": {
        "description": "Any Valid timezone, for example:UTC, Pacific Standard Time. Refer: https://msdn.microsoft.com/en-us/library/gg154758.aspx"
      }
    },
    "dailyRetentionDurationCount": {
      "type": "int",
      "metadata": {
        "description": "Number of days you want to retain the backup"
      }
    },
    "location": {
      "type": "string",
      "defaultValue": "[resourceGroup().location]",
      "metadata": {
        "description": "Location for all resources."
      }
    }
  },
  "resources": [
    {
      "apiVersion": "2016-12-01",
      "name": "[concat(parameters('vaultName'), '/', parameters('policyName'))]",
      "type": "Microsoft.RecoveryServices/vaults/backupPolicies",
      "location": "[parameters('location')]",
      "tags": null,
      "dependsOn": [
        "[concat('Microsoft.RecoveryServices/vaults/', parameters('vaultName'))]"
      ],
      "properties": {
        "backupManagementType": "AzureIaasVM",
        "retentionPolicy": {
          "dailySchedule": {
            "retentionDuration": {
              "count": 30,
              "durationType": "Days"
            },
            "retentionTimes": [
              "2018-06-07T01:00:00+00:00"
            ]
          },
          "retentionPolicyType": "LongTermRetentionPolicy",
          "weeklySchedule": null,
          "monthlySchedule": null,
          "yearlySchedule": null
        },
        "schedulePolicy": {
          "schedulePolicyType": "SimpleSchedulePolicy",
          "scheduleRunDays": null,
          "scheduleRunFrequency": "Daily",
          "scheduleRunTimes": [
            "2018-06-07T01:00:00Z"
          ],
          "scheduleWeeklyFrequency": 0
        },
        "timeZone": "[parameters('timeZone')]"
      }
    }
  ]
}
```

**Comment by Fred-sun** [comment]
@yungezz Could you take a look this contributor update?

**Comment by yungezz** [comment]
@ajaguilar-viewnext  this is not role issue, but azure recovery service usage issue, I did  some search, and found below sample for reference. Meantime, I'll close the issue. pls cut new issue if met any error from azure_preview_modules
```
schedulePolicy":{"schedulePolicyType":"SimpleSchedulePolicy","scheduleRunFrequency":"Daily","scheduleRunTimes":["2017-10-19T17:00:00Z"],"scheduleWeeklyFrequency":0}
```

**Comment by codycodes** [comment]
For those who may have had the same issue, the fix is to ensure that `scheduleRunTimes` is stored as an array:

```
"scheduleRunTimes": ["2017-10-19T17:00:00Z"]
```

Currently you also must use the square brackets notation `[]` when running these ARM templates directly on the parameters input page from Azure (see image). The error checking is not currently developed well enough to let you know it's misinterpreting the data type.

![image](https://user-images.githubusercontent.com/8005593/48681556-f632b300-eb57-11e8-92f5-b68079653ee9.png)
